### PR TITLE
France: Updated localadmin and locality records

### LINKED ISSUE #1277: France locality vis-a-vis localadmin
Following up from https://github.com/whosonfirst-data/whosonfirst-data/issues/1094 where we added new and correct `localadmin` shapes let's now figure out which are **coterminous** with existing `locality` records and clean those up (the `locality` shapes are generally poor compared to the new `localadmin` shapes).

Suggested approach is to find the **coterminous** features and then instead of carrying around 2 records let's recast the `localadmin` as a `locality` with a **placetype_alt** of `localadmin`, and for the `locality` that aren't coterminous keep them as-is for now. (Which means deprecating some new `localadmin` into the existing `locality` records but adding props and &etc).

Possible problems: non-coterminous localities might still be at the boundary of a new localadmin but not be clipped by that localadmin. That's sad, but probably beyond the scope of this issue. Our hypothesis is most of the coterminous ones will clean up 70%+ of these boundary inconsistencies leaving a few rural areas funky but overall much much better.

### LINKED ISSUE #1351: Wrong `fra_x_preferred` for Saint-Alban (101750685)
In [101750685](https://spelunker.whosonfirst.org/id/101750685/) properties, `Alban de Verulamium` is the preferred french name.

This is not correct, the preferred name is `Saint-Alban`.

That means that all these properties are also wrong: `bre_x_preferred` `cat_x_preferred` `deu_x_preferred` `ita_x_preferred` `nld_x_preferred` `por_x_preferred` `rus_x_preferred` `spa_x_preferred` `srp_x_preferred` (these are translations of `Alban de Verulamium`)

### PR DESCRIPTION
**Pull request by stepps00**
Fixes #1277.
Fixes #1351.

Updates to the locality and neighbourhood placetype in France.

**Included changes:**

- [x] Mark each `locality` and `localadmin` as **coterminous** with each other
- [x] Change existing `locality` to use the same larger geom used for `localadmin` now
- [x] Save existing `locality` polygons as alt geoms
- [x] Retain locality **label centroids**
- [x] Set **nav centroid** for `localadmin` to the **locality's** label centroid
- [x] Mark `localadmin` as **hierarchy_label** = 0
- [x] In places where there is `localadmin` coverage, but no `locality` coverage, create a **new** `locality` with the `localadmin` shape
- [x] If there are extra existing `locality`s within the `localadmin` that don't share the name, then demote them to placetype `neighbourhood`.
    - [x] Point geometries
        - [x] Tag as `min_zoom` of 14.
    - [x] Polygon geometries
        - [x] Tag as `min_zoom` of 14.
        - [x] Their geometry should still be cleaned up to not spill across the locality / localadmin boundaries as proposed in https://github.com/whosonfirst-data/whosonfirst-data/issues/1277#issuecomment-430400745, but limited in scope and we delete the orphaned no-name pieces.
- [x] Validate all geometries (both new and old)
- [x] Verify records in Paris, Lyon, and Marseille are correct (these three communes have "special" status)
- [x] Update `lbl:` properties for Paris, Lyon, and Marseille
- [x] Update `localadmin` "Arrondissemont" records in Paris, Lyon, and Marseille, supersede into `borough` records

**To do:**

- [x] QA changes to all records (ensure no gaps in coverage, all props are set correctly etc)
- [x] PIP records

### CODE REVIEW

**Comment by stepps00** [comment]
6a70c09 - take care of ~480 duplicate locality sets in France
  - In a small amount of cases, we have duplicate locality features in France that should just be a single feature. This commit takes care of those duplicate sets before beginning the geom swapping.

0f3d326 - tag locality/localadmin matches as coterminous, swap geoms, add props
  - This includes the majority of updates in this PR. For any (~30k) locality/localadmin matched pair, tags the records as coterminous, updates the locality geom, saves existing locality geom as an alt, adds nav centroids.

684e67c - duplicate localadmin records where there are no localities
  - In cases where there are localadmin with no matched child locality, this commit creates a new locality record by copying the localadmin, tagging as coterminous.

ed4c42a - make them localities, verify new ids
  - A follow-up to convert the new, duplicate localadmin records as localities, verifying new wof:ids.

0fc4f46 - rework forty locality/localadmin sets, superseded, coterminous, new g...
  - There were 45 interesting cases of duplicate matches (based on name+lat+long), that were caught for further review. This commit updates 40 of those match sets.

09092a9 - take care of swapping geoms and coterminous work for five cases of ne...
  - This commit takes care of the remaining 5 match sets.

430fe5f - demote leftover locality points to neighbourhoods, update props as ne…
  - This commit supersedes any "leftover" locality records with a Point geometry that did not match to a localadmin record into a new neighbourhood record

191161b - flag the new neighbourhoods with min_zoom 14.0
  - Updates the min zoom of these new neighbourhood records to = 14.0


To do:

- QA changes
- Move the  "leftover" locality records with a Polygon/MultiPolygon geometry that did not match to a localadmin record into a new neighbourhood record, clipping geometries to localadmin boundaries
  - there are less than 1300 of these cases

**Comment by nvkelso** [comment]
On the home stretch!

**Comment by stepps00** [comment]
Also, ensure that Paris, Lyon, and Marseille (and descendants) are correct - these three areas have specific hierarchy, different than the rest of France.

**Comment by nvkelso** [comment]
Please also set these as controlled:

- **locality label centroids** for the "existing" features (don't set as controlled for "new" localities / localadmin dups – those ~10% should really get better locality label centroids anon, please file an issue)

**Comment by nvkelso** [comment]
Generally this looks good, but per the outstanding QA step please generate feature collections of all the new France **locality** and **localadmin** so we an review in QGIS together to verify the end result.

THEN OFF TO PIP'ing!

**Comment by nvkelso** [comment]
We looked at this together on screen in QGIS and it's good enough to take to PIP!

A few minor notes before then:

- Lyon has junk 4th Arrondissement and label
- Marseille has junk 16th Arrondissement and label
- localadmin in Paris, Lyon, and Marseille  to borough placetype so we don't have funky hierarchies.

screen shot 2018-10-26 at 4 14 13 pm
screen shot 2018-10-26 at 4 15 31 pm


And a random rural area showing black bold locality label XY and brown uppercase localadmin labels, looks great!

screen shot 2018-10-26 at 4 17 20 pm

**Comment by stepps00** [comment]
Noting that the "to do" list in the initial comment has been updated with tasks to complete before merge.

**Comment by orangejulius** [comment]
Nice. @joxit will want to know about this :)

**Comment by stepps00** [comment]
I've updated Lyon, Paris, and Marseille, as well as the descendant Arrondissement records in the three most recent commits.

This PR should be ready to PIP, tagging @nvkelso for a second glance.

**Comment by nvkelso** [comment]
@stepps00 Looks good, let's PIP it and review one last time.

**Pull request merged**
