### PR TITLE
Mesoshapes county 1.0 cleanup - Japan

### PR DESCRIPTION
**Pull request by stepps00**
This PR cleans up mesoshape `county` features in Japan. 
In some cases, a `county` feature was imported more than once, so the commits take care of:

- Deprecating, adding `edtf:deprecated` date and `mz:is_current` properties, and adding a `superseded_by` value to a duplicate `county` feature.
- Adding `supersedes` values to the kept `county` features.
- Exportifying to update `lastmodified` dates.

This PR should **only** update features in Japan.

### CODE REVIEW

**Comment by nvkelso** [comment]
LGTM

**Comment by thisisaaronland** [comment]
Initial merge complete: https://github.com/whosonfirst-data/whosonfirst-data/commit/253a9a3b6bfdfe749c2939b36b87abc0f22c5ec5

Now ensuring `wof:parent_id/repo`

**Comment by thisisaaronland** [comment]
Processing in dry-run mode.

**Comment by thisisaaronland** [comment]
Halted pending processing smaller PRs/weekend

**Pull request merged**
