### PR TITLE
Deprecated duplicate, bunk Nong record

### PR DESCRIPTION
**Pull request by stepps00**
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/947.

When #660 landed, the record `421174877.geojson` slipped into the `data/110/841/612/5/` filepath. This duplicate file should never have been added, so it was:

- Deprecated
- Given an `mz:is_current` of `0`

Since the filepath and id don't match, I am unable to use the exportify tool.. but I've verified the JSON is correct.. The actual `data/110/841/612/5/1108416125.geojson` is fine as is and does not need any updates.

File(s) in GitHub, for reference: https://github.com/whosonfirst-data/whosonfirst-data/tree/master/data/110/841/612/5

### CODE REVIEW

**Comment by nvkelso** [comment]
Please also point it (superseded by, even though we're deprecating it correctly?) to the legit record.

**Comment by stepps00** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/pull/968#issuecomment-334520982 fixed in ef4a5cd.

**Comment by nvkelso** [comment]
As long as @thisisaaronland thinks the paths are okay, then I'm fine here.

**Comment by thisisaaronland** [comment]
Seems fine to me.

**Comment by stepps00** [comment]
https://whosonfirst.mapzen.com/boundaryissues/pipeline/371/

**Pull request merged**
