### PR TITLE
New mz:country property for country records

### PR DESCRIPTION
**Pull request by stepps00**
This PR fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/155.

Using a modified version of [this script](https://github.com/mapzen/whosonfirst-toolbox/blob/master/scripts/add-field.py), a new `mz:country` field was added to all country records in WOF. There was one exception -  [Somaliland](https://whosonfirst.mapzen.com/spelunker/id/85632733/#7/9.773/45.805), which does not have an alpha-3 iso code. PR does the following:
- Adds `mz:country` field based on the country's `iso:country` code
- Updated `lastmodified` date

For now, this field addition will only be done to WOF country records, but country descendants may be updated in the future.

References:
- https://en.wikipedia.org/wiki/ISO_3166-1
- http://www.iso.org/iso/home/standards/country_codes.htm
- http://www.nationsonline.org/oneworld/country_code_list.htm

### CODE REVIEW

**Comment by nvkelso** [comment]
@stepps00 Generally yes, but Mapzen doesn't have an opinion about alpha-2 versus alpha-3 codes so I'd prefer this go into `wof:country_alpha3` (paired with existing `wof:country`) instead of `mz:country`. Please update this PR to use that property name instead. Please let Pelias know about the name change.

For Somaliland, Natural Earth has a 3 character code of `SOL`, let's copy that (but keep using `XS` for 2 char default).

**Comment by nvkelso** [comment]
Also, make sure to upload your customized script(s) for this to the Toolbox.

**Comment by thisisaaronland** [comment]
Mapzen _does_ have an opinion about this. It's being done for the Pelias team.

**Comment by nvkelso** [comment]
The proposed 3-char alpha values in `mz:country` _don't_ share the same existing 2-char alpha values as `wof:country`. That's confusing, especially when the existing `iso:country` and `wof:country` _do_ share the same potential range of values. 

I'd rather emphasize the 3-char alpha code lookup / extension of country as `wof:country_alpha3` to establish it's the "same" as `wof:country` but different.

**Comment by nvkelso** [comment]
But it's not different that WOF's opinion, it's just a 3 char code instead of 2 char. Either it should go in wof or Pelias should do the lookup  on their own.

**Comment by nvkelso** [comment]
@stepps00 I talked with @thisisaaronland and we're good to go with `wof:country_alpha3`.

**Comment by stepps00** [comment]
Latest commit removed the `mz:country` property and replaced it with the `wof:country_alpha3` property. Files should be ready for merge to master.

Back to @nvkelso

**Comment by nvkelso** [comment]
LGTM, over to @thisisaaronland to update meta files and merge.

**Pull request merged**
