### PR TITLE
Updates to Finland region records

### LINKED ISSUE #511: Update correct wof:lang for Finnish regions
The following regions incorrectly specify `eng` in `wof:lang`, which should be removed.

```
Uusimaa region 85683067                   
Southwest Finland region 85683073         
Tavastia Proper region 85683077           
Kymenlaakso region 85683081               
Päijänne-Tavastia region 85683085         
Paijanne Tavastia region 85683091         
Pirkanmaa region 85683099                 
South Karelia region 85683103             
Southern Savonia region 85683109          
Southern Ostrobothnia region 85683113     
Central Finland region 85683117           
Ostrobothnia region 85683119              
Central Ostrobothnia region 85683125      
Northern Savonia region 85683131          
North Karelen region 85683133             
Kainuu region 85683137                    
Northern Ostrobothnia region 85683143     
Lapland region 85683147                   
```

Also, the two records for Päijänne-Tavastia (85683085 and 85683091) should be merged.

This is related to pelias/wof-pip-service#62

### PR DESCRIPTION
**Pull request by stepps00**
Fixes #511.

This PR includes the following:

* Removed `eng` from `region` records listed in the initial issue comments (additional language source [here](https://en.wikipedia.org/wiki/List_of_municipalities_of_Finland_in_which_Finnish_is_not_the_sole_official_language)).
* WOF has two records for the `Paijanne Tavastia` region in Finland ([1](https://whosonfirst.mapzen.com/spelunker/id/85683085), [2](https://whosonfirst.mapzen.com/spelunker/id/85683091)), the feature with the smaller geometry (light blue, below) was merged with the larger geometry (dark blue, below).
* Concordance data was copied to the kept record's attributes
* Superseding work was done (no deprecated/cessation work needed because the area gained was less than 50%).
* Exportified

screen shot 2016-11-08 at 2 05 55 pm

### CODE REVIEW

**Comment by hannesj** [comment]
Thanks!

**Comment by nvkelso** [comment]
Nice work! 

Only thing I see is `85683085` needs a deprecated date.

**Comment by stepps00** [comment]
Most recent [commit](https://github.com/whosonfirst-data/whosonfirst-data/pull/514/commits/553116a9600d20c9344b4dca633f20000459c08b) added a deprecated date to `85683085`. Ready for merge.

**Comment by nvkelso** [comment]
LGTM, over to @thisisaaronland

**Comment by stepps00** [comment]
Assigning this PR back to myself to re-work the `wof:lang*` properties since `wof:lang` has since been deprecated in favor of `wof:lang_x_spoken` and `wof:lang_x_official`.

For these records, propose the following changes:

- `wof:lang_x_spoken` = eng, fin, swe
- `wof:lang_x_official` = fin, swe

**Pull request merged**
