### PR TITLE
New admin0 naturalearth props, alt_geoms, and empire geoms

### LINKED ISSUE #103: Add concordance with Natural Earth admin-0 countries
Natural Earth has unique, stable country codes (alpha-3), we should add concordance to those, and import the Natural Earth properties. That'll also get us more GeoNames.org and WOE GeoPlanet ID concordances.

### PR DESCRIPTION
**Pull request by stepps00**
Fixes #103 and #335.

This PR includes the following updates:

- Using the admin0 file from Natural Earth, joined Who's On First records on the `ne:adm0_a3` property. 
- Added ne concordance for `ne:adm0_a3` property
- Added missing Natural Earth properties to existing WOF `empire` records (example: `data/136/253/037/136253037.geojson`). 
- Added new geometries (previously missing) to existing `empire` records.
- Created new "clipped" admin0 alt-geometry files that do not extend into lakes and water bodies ("lakes" file).

### CODE REVIEW

**Comment by stepps00** [comment]
To do: concordance for empire records.

**Comment by nvkelso** [comment]
Based on new empire in https://github.com/whosonfirst-data/whosonfirst-data/pull/763/files you'll need to add same details to the Netherlands empire.

**Comment by stepps00** [comment]
Per https://github.com/whosonfirst-data/whosonfirst-data/pull/786#issuecomment-301631232:

Added all Natural Earth props, geometry, and concordance to the Netherlands empire record in the last two commits ([1](df5a6aa), [2](fc01d68)).

**Comment by stepps00** [comment]
So... New Zealand is just too big.

Preferring the master feature, which is just missing the following concordance:

"ne:adm0_a3":"NZL"

Try adding that in Boundary Issues instead.

**Pull request merged**
