### PR TITLE
Geonames names import

### PR DESCRIPTION
**Pull request by stepps00**
WIP.

This PR includes new `name:*` properties from the Geonames alternatenames.txt file. I want to spot-check records before merge, but no additional work should be needed.

List of the records updated [here](https://github.com/whosonfirst-data/whosonfirst-data/files/1184461/gn_names_diff.txt).

### CODE REVIEW

**Comment by stepps00** [comment]
@nvkelso - I've spot-checked the diff of this branch and haven't found any issues.

7dc6415 is the commit that added new locality records.

**Comment by stepps00** [comment]
Note: This does not include updates to New Zealand.... 

Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/834

**Comment by nvkelso** [comment]
@stepps00 Can you replay your last commit against master, please to cleanup these merge conflicts? If that takes too much time then rerun the script against master in a clean branch.

**Comment by stepps00** [comment]
I reset this branch hard to master and cherry picked the original commit on top. The resulting changes are in https://github.com/whosonfirst-data/whosonfirst-data/pull/874/commits/a6d512f6dc235a10688eb5c4be8778dc113b59fe.

There are **118,750 files modified**, no additions, no conflicts. See full list in this GIST: https://gist.github.com/anonymous/70f53fc6d404e8c72a14b937d43211e1.

**Comment by stepps00** [comment]
Talked with @nvkelso IRL and we'll ignore New Zealand now. This is ready for review.

**Comment by stepps00** [comment]
Related script to run this again is in https://github.com/mapzen/whosonfirst-toolbox/pull/18.

**Comment by nvkelso** [comment]
@stepps00 I'm seeing many `name:unk_x_variants` here and looking at your script I see you already guard against GeoName dups that are already in the English or Russian slot so these are the remainder (that are different than existing English or Russian preferred or variant names). _Most_ of these look like English to me, but some of them aren't. Can you add an issue and relate it here to do some language detection on these `name:unk_x_variants` values post-merge and either assume English or move to the detected language, please?

**Comment by stepps00** [comment]
@nvkelso - new issue here: https://github.com/whosonfirst-data/whosonfirst-data/issues/880

**Comment by nvkelso** [comment]
I've added some examples to #880 but I don't see any problems with this PR, let's merge it.

Over to @thisisaaronland, property only edits (no PIPing).

**Pull request merged**
