### PR TITLE
Update City of * records

### PR DESCRIPTION
**Pull request by stepps00**
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/971.

This PR takes care of all "City of *" locality point records in the US. The only "leftover" records are the following:

- [102526247](https://whosonfirst.mapzen.com/spelunker/id/102526247), City of Colorado Springs Airport, a valid campus.
- [420512551](https://whosonfirst.mapzen.com/spelunker/id/420512551), City of Temple Terrace (a valid, non-qs_pg locality)
- [85929465](https://whosonfirst.mapzen.com/spelunker/id/85929465), City of Creede (a valid, non-qs_pg locality)
- [85977105](https://whosonfirst.mapzen.com/spelunker/id/85977105), City of the Sun (a valid, non-qs_pg locality)

### CODE REVIEW

**Comment by nvkelso** [comment]
Are there any `"County of"` or `"City and County of"` or similar to also think about?

**Comment by stepps00** [comment]
I'll take a look at all `County of *` records once I commit the `City of *` changes.

**Comment by stepps00** [comment]
Re https://github.com/whosonfirst-data/whosonfirst-data/pull/1025#issuecomment-341844478: 

Happy to report that there are only two "County of" / "City and County of" records ([1](https://whosonfirst.mapzen.com/spelunker/id/85684081/), [2](https://whosonfirst.mapzen.com/spelunker/id/85683751)), neither of which were imported from the Quattroshapes point gazetteer work.

**Comment by stepps00** [comment]
@nvkelso - untagged this as "WIP". Ready for review, unless this PR should include:

- Another API run to catch the remaining deprecated records that were not superseded (~10% of them)
or
- Any records should be tagged with `"mz:is_current":1`

**Comment by nvkelso** [comment]
@stepps00 Wither the 800 that didn't match a polygon? I suspect this is caused by two cases:

1. Locality point is too far to be "near" or perfectly "inside" the intended polygon, but there should have been a match.
2. We have 2 points, highly unlikely (more likely there are dup points in the qs_pg import, since the original qs import was polygons only).
3. It's just a legit point, but we should move the "City of..." name to variant, and reset default name to just the ... part.

**Comment by nvkelso** [comment]
Noting here the the superseded records will be a mix of placetypes (mostly `locality`, some `localadmin`) based on the vagaries of Geonames hierarchy and our import logic, so that's okay. 

Also noting here that if the "City of..." record was imported as not-current then it's expected to not have a full hierarchy – but the thing it's being superseded into should have one already (no additional work needed).

**Comment by nvkelso** [comment]
Generally the API PIP matching seems to be working as expected, so once my comments in https://github.com/whosonfirst-data/whosonfirst-data/pull/1025#issuecomment-342978373 are addressed 👍.

**Comment by nvkelso** [comment]
Of the 800 unresolved, @stepps00 used a new config for Mapzen Places search (hat tip to Aaron) in https://github.com/whosonfirst-data/whosonfirst-data/pull/1025/commits/88da72c0024038a2a57a2de10905de70adc5c1fd and https://github.com/whosonfirst-data/whosonfirst-data/pull/1025/commits/1ebd18e24c5472983728f590e7962070c599da75. We think there are less than 200 left after that. Time to move on – let's merge this.

**Comment by nvkelso** [comment]
Fix more merge conflicts, OMG.

**Comment by nvkelso** [comment]
Since the changed records are just point geoms we can go thru the pipeline. Over to @stepps00.

**Comment by stepps00** [comment]
https://whosonfirst.mapzen.com/boundaryissues/pipeline/518/

**Pull request merged**
