### PR TITLE
Min zoom updates - non-matched features

### PR DESCRIPTION
**Pull request by stepps00**
This PR includes 1,542 new records from the `ne_10m_populated_places.shp` file.

All records have been exportified, given required properties, and all `ne:*` properties (no special cases, as discussed). 

This follow-up to https://github.com/whosonfirst-data/whosonfirst-data/pull/846.

### CODE REVIEW

**Comment by nvkelso** [comment]
Were these matched with any existing WOF features? (Using the meesoshapes import script.)

**Comment by stepps00** [comment]
These features were the "leftovers" that did not match on the first round of `ne` concordance matching, and were imported as completely new records. 

I can run them through a modified version of the mesoshapes import script (they have different props and attributes to take into account) and adjust the PR accordingly.

**Comment by nvkelso** [comment]
IRL: look at the quattroshapes point gazetteer import script instead (there are some that we spot checked that are already in WOF).

Also, `mz:min_zoom` needs to be additionally set off the `ne:min_zoom` value.

**Comment by stepps00** [comment]
Closing in favor of https://github.com/whosonfirst-data/whosonfirst-data/pull/851

**Pull request closed without merging**
