### PR TITLE
Deprecated new point neighbourhoood records in previously curated areas

### LINKED ISSUE #972: Deprecate imported neighbourhoods in our curated cities
This is a followup from reviewing https://github.com/whosonfirst-data/whosonfirst-data/pull/824#issuecomment-334619360.

Don't bother figuring out what to superseded them into just deprecate them en mass by intersecting with the polygons of the curated neighbourhoods (e.g. the ones in #945).

- `Central Waterfront` (is a dup, but ignore)
- `West of Twin Peaks` (looks to be new, but deprecate anyhow)

### PR DESCRIPTION
**Pull request by stepps00**
Fixes #972.

- Moves the `edtf:cessation` property to the `edtf:deprecated` property and resets the `edtf:cessation` to `"uuuu"` for any "non-current" `qs_pg`-sourced neighbourhood records.
- Deprecated any new `qs_pg`-sourced neighbourhood record in any of the ~75 localities that we've curated by hand.
- Used the API to supersede the point geometry records into the polygon record that it falls within.

I also deprecated point records that were just outside of curated markets, an example being `112/609/115/5/1126091155.geojson`, which falls _just_ outside of the Vancouver boundary.

### CODE REVIEW

**Comment by stepps00** [comment]
Property-only edits, no affected descendant records. Can run this through the pipeline.

**Comment by nvkelso** [comment]
@stepps00 can you list out the IDs of the changed features for me here so I can preview the affected files in QGIS, please?

**Comment by stepps00** [comment]
@nvkelso - Here's a list of all files updated in this PR: [updated_ids.txt](https://github.com/whosonfirst-data/whosonfirst-data/files/1458998/updated_ids.txt)

**Comment by nvkelso** [comment]
Let's review this together Thanksgiving week – including investigation why some features are being superseded_by 2 or more other features – or some master features are superseding 10 features.

**Comment by stepps00** [comment]
@nvkelso - I fixed https://github.com/whosonfirst-data/whosonfirst-data/pull/1029#issuecomment-345401971 via https://github.com/whosonfirst-data/whosonfirst-data/pull/1029/commits/0f0a8693249f59c60a595a78aa63e76d611505d7. Any other multi-superseding cases should be valid.. this PR is ready for review (can be put through the pipeline).

**Comment by stepps00** [comment]
https://whosonfirst.mapzen.com/boundaryissues/pipeline/522/

**Pull request merged**
