### PR TITLE
New US region (state) alt-geometries

### PR DESCRIPTION
**Pull request by stepps00**
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/524

This PR includes new alt-geometry shapes for all regions parented by the United States. These geometries are clipped to coastlines.

### CODE REVIEW

**Comment by nvkelso** [comment]
Can you describe where these geometries were sourced and how additional coast clipping was performed, please? When I zoom into the coast it looks low-resolution (like 1:100,000 instead of 1:10,000). See American Samoa or [Pennsylvania](https://github.com/whosonfirst-data/whosonfirst-data/blob/9ca5fb8de5b11c3785d320efe9227f81dc52c024/data/856/884/81/85688481-alt-uscensus.geojson). See image below.

For the filenames, can you add an indication that these geometries are `land` or `clipped` or something? The quattroshape source is actually US Census, too, and includes the land + water, so we need something to differentiate these. See some discussion of this in: https://github.com/whosonfirst-data/whosonfirst-data/issues/367.

screen shot 2016-11-29 at 21 37 06

**Comment by stepps00** [comment]
These alt-geometry shapes were taken directly from the Census' Cartographic Boundaries Shapefiles collection (link [here](https://www.census.gov/geo/maps-data/data/cbf/cbf_state.html)). No additional clipping was performed; the generalized coastline is due to the 500k scale (1:500,000). Three thoughts:

- After tracing the `uscensus` sources file ([here](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/uscensus.json)) url link, it looks like that source directs you to a download for the source shapes used by quattroshapes. Since we're using a different Census link and file, are we comfortable appending the new link to the existing source file? Or should a new source be created?

- I propose we use a filename like `85668127-alt-uscensus-500k.geojson`, thoughts?

- If that filename works, I'll need to also include the following in each default record's properties:

``` 
"src:geom_alt":[
        "uscensus-500k"
 ],
````

@nvkelso

**Comment by nvkelso** [comment]
These sound like `display` geometries (see https://github.com/whosonfirst-data/whosonfirst-data/issues/538#issuecomment-263814171) at `zoom-10`, featuring mostly "land" inclusive of terrestrial waters. For Binx they would work, but not for zoomed in map display (we'd want an additional display set at say `zoom-16`, which is the max_zoom we use in Tilezen).

- agree with `uscensus` as _source_
- suggest `display` as the _intended-use_
- suggest `terrestrial` as the _level-of-scope_
- suggest `zoom-10` as the _level-of-detail_
- all together: `85668127-alt-uscensus-display-terrestrial-zoom-10.geojson`
- and in the master record: `"src:geom_alt":[ "uscensus-display-terrestrial-zoom-10"],`

Where geometry clipping (level-of-scope) is one of:

- `original` - from the source, whatever they did
- `territorial` - default optimized for revGeo inclusive of all marine and territorial waters (no water clipping), understood that Mapzen may have modified the original, but it's still "sourced" to the source.
- `terrestrial` - clipped to land + terrestrial waters (e.g. clipped to ocean coastline, but not punched thru for large inland water bodies), understood that Mapzen may have modified the original, but it's still "sourced" to the source. Used for most choropleth maps.
- `land` - no marine waters, no inland waters. Used in contexts where someone doesn't want to load separate "earth" base or "water" top layers. This matches Tilezen's kind value (terrestrial is more the general catch all for the Tilezen layer). The computed label position should be based on this geometry, when available.
- `marine` - geometric opposite of terrestrial, useful for boundary lines.

Here's table converting 1:x representative fractions (eg: `1:500k`) into web map zooms ([src](http://kelsocartography.com/blog/?p=2407)), with some integer rounding:

scales_table

**Comment by nvkelso** [comment]
LGTM

**Comment by stepps00** [comment]
For future reference, script to update the `src:geom_alt` field was imported to the `whosonfirst-toolbox` repo ([here](https://github.com/mapzen/whosonfirst-toolbox/blob/master/scripts/issue524-alt-src-handling.py)). 

The write-up for alt-geometries in there `whosonfirst-cookbook` repo ([here](https://github.com/whosonfirst/whosonfirst-cookbook/blob/master/how_to/creating_alt_geometries.md)) will be updated shortly.

**Comment by thisisaaronland** [comment]
Just to put this in the standard nomenclature for alt geometry names:

* source == `source`
* intended-use == `function`
* level-of-scope and level-of-detail == `extras`, which is an arbitrary array of extras left to the discretion of `source` + `function`

If we need to be precise about what's allowed that information should be encoded in the relevant record in https://github.com/whosonfirst/whosonfirst-sources/

**Comment by stepps00** [comment]
Most recent commit adds the source name (`uscensus`) to the filenames of the alt-geometry files. 

This PR is ready to merge to `master`.

**Pull request merged**
