### PR TITLE
Updated macroregion records in France

### PR DESCRIPTION
**Pull request by stepps00**
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/208.

This PR updates the geometries and records for `macroregion` records in France. On 01-01-2016, the `macroregion` records in France were consolidated. This PR includes the following work:

- Merged geometries of pre-2016 macroregions to create geometries for new macroregion records. Imported these merged geometries in new macroregion records.
- Added `wof:supersedes` property values to new records 
- Added `wof:superseded_by`, `mz:is_current`, and `mz:cessation` property values to outdated records

Files removed from S3, this PR should include all required updates.

### CODE REVIEW

**Comment by nvkelso** [comment]
Will require PIPing.

**Comment by stepps00** [comment]
@thisisaaronland - I'm not seeing these 23 new French `macroregion` records in the Spelunker, but I do see them in GitHub ([here](https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/110/882/639/3/1108826393.geojson)) and in S3. Any idea why that is?

**Comment by thisisaaronland** [comment]
Maybe just bunk indexing. I can re-run that by hand.

**Comment by stepps00** [comment]
Note: All records updated in this PR now appear in the Spelunker.

**Pull request merged**
