### PR TITLE
Mesoshapes import 1.0 cleanup - Thailand

### PR DESCRIPTION
**Pull request by stepps00**
This PR fixes issues at the `admin2` level in Thailand.

The mesoshapes import file for Thailand included 807 `admin2` features, but Who's On First currently has 720 `admin2` features. A breakdown of how this is issue was fixed in this PR:

- Commit 8a2ab1c edited 38 `admin2` features in Thailand that had more than one value in the `"src:alt_geom"` field to only include one value of `"mesoshapes"`.
- Commit f74b69b Reverted 38 features to the pre-mesoshapes import state.
- Commit 8e5cb20 Removed 38 bunk alt_geom files.
- Commit 9942b32 Deprecated 9 bunk features that were never correct to begin with.
- Commit b2f60ca Updated 38 records with new mesoshapes features and imported all leftover `admin2` features as new to Who's On First.

### CODE REVIEW

**Comment by nvkelso** [comment]
Ready for PIPing.

**Comment by thisisaaronland** [comment]
@stepps00 - this has merge conflicts, can you fix these please.

**Comment by stepps00** [comment]
Most recent commits take care of any merge conflicts, over to @thisisaaronland.

**Comment by stepps00** [comment]
The PR for this issue was actually merged to master last week. Some git funkiness is showing files in conflict, but everything looks OK in master. 

Nothing more to do here, closing issue.

**Pull request closed without merging**
