### PR TITLE
Mesoshapes Import - Round One

### PR DESCRIPTION
**Pull request by stepps00**
First PR with new mesoshape features for import (!!!). PR includes county features for the following 20 countries:

**12** countries with "fresh imports" (countries that currently have no existing WOF county records):

**D.R. Congo**
**French Guiana**
**Guyana**
**Haiti**
**Kosovo**
**Kyrgyzstan**
**Liberia**
**Mauritania**
**Mozambique**
**Papua New Guinea**
**Sudan**
**Suriname**

**8** countries with "mapped imports" (countries that currently have WOF county records that were manually entered in the mesoshapes geojson files):

**Chad** _(Two existing county records mapped cleanly to mesoshapes)_
**Cuba** _(One existing county record mapped cleanly to mesoshapes)_
**Gabon** _(Three existing county records mapped cleanly to mesoshapes)_
**Kenya** _(Four existing county records mapped cleanly to mesoshapes)_
**Palestine** _(One existing county records mapped cleanly to mesoshapes)_
**South Sudan** _(One existing county records mapped cleanly to mesoshapes)_
**Tajikistan** _(One existing county records mapped cleanly to mesoshapes)_
**Yemen** _(Three existing county records mapped cleanly to mesoshapes)_

These countries have descendants, so we'll need to hold off on import until with re-PIP the descendants.

### CODE REVIEW

**Comment by nvkelso** [comment]
Lots of re-PIPing to do!

One thing to note for the script is we go and get the `wof:id` of the region looking at the `meso:admin_1`, but it doesn't look like we record that in the `wof:belongsto` or `wof:hierarchy` (and we should).

```
 +    "meso:admin_1":"Orientale",
 +    "meso:name_local":"Kisangani",
 +    "wof:belongsto":[
 +        85632643
 +    ],
 +    "wof:country":"CD",
 +    "wof:hierarchy":[
 +        {
 +            "country_id":85632643,
 +            "county_id":1091679655
 +        }
 +    ],
```

**Comment by nvkelso** [comment]
Kenya's country code is KE not XK:

`iso:country:XK`
`wof:country:XK`

**Comment by nvkelso** [comment]
Looks like Kosovo and Kenya got mixed up (there are 2 Kenyas, delete the country records with XK and rerun Kosovo).

**Comment by stepps00** [comment]
@nvkelso - the original Kosovo shapefile _was_ mixed up with Kenya and given incorrect geometries. In [the most recent commit](https://github.com/whosonfirst-data/whosonfirst-data/commit/a6e84a1c14e8000cefdbfe47074d8c28a9501b89), the Kovoso records with Kenyan geometries were removed and new, correct Kosovo records were created.

[This commit](https://github.com/whosonfirst-data/whosonfirst-data/commit/f8923470d6f7e72a90c3b970c391691566ffaebc) was the first attempt at correcting this issue, but only updated `wof:id`s, it did not correct geometries.

As of the most recent commit, all geometries in Kosovo should be correct. I will go through the countries list again to correct any _NULL_ records, as discussed.

**Pull request merged**
