### PR TITLE
Update bad French, German, Chinese and Dutch language code names

### PR DESCRIPTION
**Pull request by ndcartography**
**Objective:** Fixes https://github.com/mapzen/data-tasks/issues/33 and Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/291. Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/291.

- Migrate (then delete) any `*_x_preferred` , `*_x_variant`, `*_x_coloquial` , `*_x_historical` records that have an outdated language code:

      French    -      `fre` -> `fra`
      German    -      `ger` -> `deu`
      Chinese   -      `chi` -> `zho`
      Dutch     -      `dut` -> `nld` ~added after PR was opened

- **Example:** The `name:ger_x_preferred` record `"Falklandinseln"`would go into `name:deu_x_preferred` name, and the old `name:ger_x_preferred` record would then be deleted.

  - if a `name:deu_x_preferred` already exists, then the `name:ger_x_preferred` will be added to `name:deu_x_variant` (unless the records match exactly)
  - if `name:deu_x_variant` already has that record, the `name:ger_x_preferred` will not be added. This elimanates any duplicate records.

**Placetypes covered:**

- [x] disputed
- [x] dependency
- [x] country
- [x] region
- [x] macrohood
- [x] borough
- [x] microhood
- [x] locality
- [x] neighbourhood

**Placetypes without bad lang records
- [x] macroregion (NA)
- [x] ocean (NA)
- [x] continent (NA)
- [x] marine area (NA)

*NA - no records for bad language code

note: deprecated records will not be updated

### CODE REVIEW

**Comment by ndcartography** [comment]
NOTE:   `Updated name:eng_x_preferred with wof:name for Continents` a75f06d  randomly appeared as a commit, and does not relate to this PR.

**Comment by nvkelso** [comment]
This generally looks like I expect it to look.

Suggest removing https://github.com/whosonfirst-data/whosonfirst-data/commit/a75f06df71b9ec20c3fee034453dce4f0e51667a from this branch.

**Comment by nvkelso** [comment]
@ndcartography are `country`, `macroregion`, and `region` also complete or is this still WIP (work in progress)?

**Comment by ndcartography** [comment]
@nvkelso they are still WIP, I'm running them then spot checking for anything funky.

**Comment by nvkelso** [comment]
@stepps00 After you review please pass to @thisisaaronland (no PIPing required).

**Comment by stepps00** [comment]
This commit looks great, ready to merge to master.

Commit https://github.com/whosonfirst-data/whosonfirst-data/pull/859/commits/7b1d5dfafb76800ab64fccf1dd9e4ef4ad84afc9 reverted the `Updated name:eng_x_preferred with wof:name for Continents` commit, so this branch is now clean and without merge conflicts.

Over to @thisisaaronland for merge (prop edits only).

**Comment by stepps00** [comment]
Back to @ndcartography for `_x_unknown` updates.

**Comment by stepps00** [comment]
Note: this PR is complete, will be a top priority for merge once conflicts are taken care of.

**Comment by ndcartography** [comment]
@nvkelso @stepps00 @thisisaaronland This PR has no more merge conflicts and is ready to be merged asap.

**Comment by nvkelso** [comment]
> re: https://github.com/whosonfirst-data/whosonfirst-data/pull/859#issuecomment-315899081

@ndcartography which commit fixes the `_x_unknown` names?

**Comment by ndcartography** [comment]
@nvkelso `_x_unknown` were attempted with a crawl script that didn't give any results. I'm trying it again and will commit any changes.

**Comment by ndcartography** [comment]
@nvkelso @stepps00 all `{}_x_unknown` records have been updated along with all merge conflicts. This PR is good to go

**Comment by nvkelso** [comment]
Discussed IRL: French is the only language that had `*_x_unknown` values so we're done here.

**Comment by nvkelso** [comment]
Over to @thisisaaronland for merging (property only edits, no PIP).

**Pull request merged**
