### PR TITLE
India: Update Telangana and descendants

### PR DESCRIPTION
**Pull request by stepps00**
Related to https://github.com/whosonfirst-data/whosonfirst-data/issues/661.

This PR includes the following updates:
- Changes the name of **Telengana** to **Telangana**. This name was misspelled upon import, but the name properties are all correct, so only the `wof:name` changes.
- Added `reversegeo:*` properties to the [Hyderabad](https://spelunker.whosonfirst.org/id/102030059/) record so it correctly falls within the Hyderabad `county` record
- PIPs Telangana to update hierarchies of all descendant records (removing incorrect dual hierarchies). 

Keeping #661 open, since the original issue is to track neighbourhood updates in Hyderabad.

### CODE REVIEW

**Comment by nvkelso** [comment]
Features inside Hyderabad should still receive dual hierarchies, though, as it is the capital of the Indian state of Telangana and de jure capital of Andhra Pradesh, right?

**Comment by stepps00** [comment]
Yeah, that makes sense.

To do that, I'll need to:
- find any of the updated records in this PR with Telangana in their `wof:hierarchy`
- manually set dual hierarchies
- set `wof:controlled` properties
- update `wof:parent_id` to be `-4`

**Comment by stepps00** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/pull/1330#issuecomment-426409883 was taken care of in de05e50 and f5516d3, but I'd like to QA and set coterminous properties (locality and county of Hyderabad) before merging.

**Comment by stepps00** [comment]
QAd the changes that things look good. 

I could set swap the existing geometry of the [locality of Hyderabad](https://spelunker.whosonfirst.org/id/1108696315/) with the smaller [county of Hyderabad](https://spelunker.whosonfirst.org/id/102030059/) geometry, but that would not cause additional hierarchy changes (they're already manually set). Plus, I'm not sure if I prefer one of those geometries over the other.

Thoughts @nvkelso?

**Comment by nvkelso** [comment]
The two Hyderabad records both look wrong in different ways to me. Suggest no change for now.

**Pull request merged**
