### PR TITLE
QS point gazetteer import + names + populations

### PR DESCRIPTION
**Pull request by stepps00**
Related to #107.

This PR includes features in the QS `noimport.geojson` file (file with 450K records).
This PR does not include `county` or `region` features, as those placetypes have open PRs (#660 being the main open PR).

Notes about mismatches/duplicate concordances below.

Paging @nvkelso for review.

### CODE REVIEW

**Comment by stepps00** [comment]
Notes:

commit: 8ca83bf39c54bd2d119d9b4527d90d2279873d5e
- placetype: neighbourhood
- Note - 67620 records edited/created in the commit, 69243 features in the import file.

commit: aa238672cf5f354471052d9737c484a92e44cee7
- placetype: locality
- Note - 227594 records edited/created in the commit, 237195 features in the import file.
    
commit: 2139706d4218b42bd44f75a381c2c683a2f49ec7
- placetype: localadmin
- Note - 110893 records edited/created in the commit, 115890 features in the import file.
    
commit: 5d6b0984227c61de769d926351bcdcd6fadb31cc
- placetype: county (cessation file)
- Note - 9 records edited/created in the commit, matches the number of features in the import file.

commit: b87ae1243b4a190d2ee70cc565e5d13c0e1b189f
- placetype: locality (locality_funky file)
- Note - 2208 records edited/created in the commit, 1760 features in the import file.

commit: 510bbb2eff306e3f3adf538d1839bd6c121e0eab
- placetype: locality (locality_gp_neighbourhood_gn file)
- Note - 397 records edited/created in the commit, matches the number of features in the import file. 
	
commit: b297a8b68462df5839b055348e9afed0b7fc0bba
- placetype: country and dependency
- Note - This work impacts countries and dependencies. At this level, the only thing we're importing are duplicate concordances and point geometries for admin0-level records. Suggest removing this commit from any import PR.

**Comment by nvkelso** [comment]
Great work here!

> commit: b87ae12
> placetype: locality (locality_funky file)
> Note - 2208 records edited/created in the commit, 1760 features in the import file.

This seems weird, suggest removing commit and rerunning.

> commit: b297a8b
> re: `placetype: country and dependency` 

Let's remove that commit from this branch and do a manual match to include `wof:id` per feature and rerun script with new commit in this branch.

> others

We know there are dups in QS_PG so it's not surprising that the same existing WOF record would match for multiple QS_PG features. The overall numbers are roughly right, so let's skip investigating that more.

After the above re-evaluate the conflicting files for a clean (mergable) PR.

**Comment by stepps00** [comment]
@nvkelso, comments below (in bold):

>> commit: b87ae12
>> placetype: locality (locality_funky file)
>> Note - 2208 records edited/created in the commit, 1419 features in the import file.

> This seems weird, suggest removing commit and rerunning.

**This was reset in commit b323615 and rerun in commit 042a215.**

> > commit: 8ca83bf
> > placetype: neighbourhood
>>  Note - 67620 records edited/created in the commit, 69243 features in the import file.

> Recapping what we discussed in person on Monday, manual review of these neighbourhoods – if they are in an area of manual neighbourhood curation and didn't match (new records), then let's import those as `"mz:is_current" = 0` and give them an `edtf:cessation` date.

**Performed a "select by location" in QGIS for any new neighbourhood record with a point geometry that fell within a locality geometry that we've previously worked on, which yielded 347 records. Commit  c63bb16 updated these records to include a `"mz:is_current" = 0` property and an `edtf:cessation`property with today's date.**

> > commit: b297a8b
> > re: `placetype: country and dependency` 

> Let's remove that commit from this branch and do a manual match to include `wof:id` per feature and rerun script with new commit in this branch.

**This commit was reverted in commit ee61c90.**

> > others

> We know there are dups in QS_PG so it's not surprising that the same existing WOF record would match for multiple QS_PG features. The overall numbers are roughly right, so let's skip investigating that more.

> After the above re-evaluate the conflicting files for a clean (mergable) PR.

**Complete.**

**Comment by nvkelso** [comment]
@stepps00 Can you fix the conflicts here, please?

**Comment by stepps00** [comment]
To do for each commit in this PR:  

```
git show --pretty="" --name-only 14d2898 > ~/tmp/files-in-pr.csv

python wof-csv-to-feature-collection -p /usr/local/mapzen/whosonfirst-data/data -c ~/tmp/files-in-pr.csv -o ~/tmp/files-in-pr.geojson full -i
```

**Comment by nvkelso** [comment]
Regarding:

> commit: b297a8b
> placetype: country and dependency
> Note - This work impacts countries and dependencies. At this level, the only thing we're importing are duplicate concordances and point geometries for admin0-level records. Suggest removing this commit from any import PR.

Yes, I agree we should remove this commit. It looks like we already have some / all of that information (like GeoPlanet ids) either from the `with content` QSimport a while ago, or from other sources since. And the duplicate features it also introduces conflict with our *manicured* data for the same placetypes.

**Comment by nvkelso** [comment]
@stepps00 please fix merge conflicts.

Other than that we think this is ready for me to give one last go-over.

**Comment by nvkelso** [comment]
This PR also incorporates these improvements:

- **287k** more names
- **202k** more wof:population props

**Comment by nvkelso** [comment]
In resolving conflicts:

- Athens-Clark County is reverted back to it's earlier WOF name (versus @trescube edit on Boundary issues)
-   `85894917` wof:name reverted to **Queensbury** versus master's `Moodyville`, to be consistent with all our harvested alt names. @ZBSingleton do you know what's up with that place in Vancouver, Canada?
- A couple records seem to loose their hierarchy in master with maybe new lat/lngs? I kept the old hierarchies for those?
- Total list of 100+ files with merge conflicts that I resolved and exportified: https://gist.github.com/nvkelso/b52e26903a0104e776d2b879778561b0

**Comment by ZBSingleton** [comment]
@nvkelso That area is officially recognized by the city as "Moodyville" but can also occasionally be referred to by its main commercial area along Queensbury Avenue. It seems like this came about because of a missing eng_x_preferred update (we hadn't started updating that property until after our first multilingual market). The area should still use Moodyville as its main name with the Queensbury name as a variant.

**Comment by nvkelso** [comment]
@ZBSingleton Thanks! Fixed in https://github.com/whosonfirst-data/whosonfirst-data/pull/824/commits/b1681cceafc92d82f40c0d200c20154cecc34b74.

**Comment by nvkelso** [comment]
To review this PR I ran:

> git diff --name-only `git merge-base origin/master HEAD` | bbedit

Which resulted in both primary records and alt geoms for same:

- https://gist.github.com/nvkelso/b52e26903a0104e776d2b879778561b0#file-add-compared-to-master-txt

Stripping to just primary records:

- https://gist.github.com/nvkelso/b52e26903a0104e776d2b879778561b0#file-compared-with-master-just-primary-records-txt

I saved that out to local disk as `~/tmp/files-in-pr-824-qs_pg2.csv`, stripping to just `wof:id` column with that header and only the IDs in the rows instead of the full file paths.

Then from `/Users/nvkelso/git-repos/py-mapzen-whosonfirst-utils/scripts` I run:

> python wof-csv-to-feature-collection -p /Users/nvkelso/git-repos/whosonfirst-data/data -c ~/tmp/files-in-pr-824-qs_pg2.csv -o ~/tmp/files-in-pr-824-qs_pg2.geojson full -i

Which chugs a long time, then fails on `85633345` which is New Zealand. Remove that from the list, because GitLFS for another day. 

Then it's 3.4 GB so export fewer properties:

> python wof-csv-to-feature-collection --slim-template external_editor -p /Users/nvkelso/git-repos/whosonfirst-data/data -c ~/tmp/files-in-pr-824-qs_pg2.csv -o ~/tmp/files-in-pr-824-qs_pg2_ee.geojson -i

Which doesn't actually work. To be continued...

**Comment by nvkelso** [comment]
To review this PR I ran:

> git diff --name-only `git merge-base origin/master HEAD` | bbedit

Which resulted in both primary records and alt geoms for same:

- https://gist.github.com/nvkelso/b52e26903a0104e776d2b879778561b0#file-add-compared-to-master-txt

Stripping to just primary records:

- https://gist.github.com/nvkelso/b52e26903a0104e776d2b879778561b0#file-compared-with-master-just-primary-records-txt

I saved that out to local disk as `~/tmp/files-in-pr-824-qs_pg2.csv`, stripping to just `wof:id` column with that header and only the IDs in the rows instead of the full file paths.

Then from `/Users/nvkelso/git-repos/py-mapzen-whosonfirst-utils/scripts` I run:

> python wof-csv-to-feature-collection -p /Users/nvkelso/git-repos/whosonfirst-data/data -c ~/tmp/files-in-pr-824-qs_pg2.csv -o ~/tmp/files-in-pr-824-qs_pg2.geojson full -i

Which chugs a long time, then fails on `85633345` which is New Zealand. Remove that from the list, because GitLFS for another day. 

Then it's 3.4 GB so export fewer properties:

> python wof-csv-to-feature-collection --slim-template external_editor -p /Users/nvkelso/git-repos/whosonfirst-data/data -c ~/tmp/files-in-pr-824-qs_pg2.csv -o ~/tmp/files-in-pr-824-qs_pg2_ee.geojson -i

Which doesn't actually work. To be continued...

**Comment by nvkelso** [comment]
Looks like new hierarchies in master cause more merge conflicts. @stepps00 can you update against master again, please?

**Comment by nvkelso** [comment]
Using a newer version of collect script in https://github.com/whosonfirst/py-mapzen-whosonfirst-utils/pull/23:

> python wof-csv-to-feature-collection -l --slim-template external_editor -p /Users/nvkelso/git-repos/whosonfirst-data/data -c ~/tmp/files-in-pr-824-qs_pg2.csv -o ~/tmp/files-in-pr-824-qs_pg5.geojson -i -a /Users/nvkelso/git-repos/whosonfirst-properties/aliases/property_aliases.json -b

Which generates 340 MB file instead of a 3.4 GB file!

pasted image at 2017_10_05 03_33 pm

pasted image at 2017_10_05 03_32 pm

**Comment by nvkelso** [comment]
More preview images. Generally yellow dots are NEW added while PURPLE are existing with updates (like an alt geom or population or names).

**Humboldt county, California:**

screen shot 2017-10-05 at 16 18 09

**Still in Humboldt, traveling south along Avenue of the Giants:**

screen shot 2017-10-05 at 16 18 33

San Francisco:

screen shot 2017-10-05 at 16 19 14

**Hyattsville, Maryland:**

screen shot 2017-10-05 at 16 20 43

**Lancaster, PA:**

screen shot 2017-10-05 at 16 22 14

**London:**

screen shot 2017-10-05 at 16 23 38

**Comment by nvkelso** [comment]
I only see 1 merge-block problem to work thru related to duplicate `src:geom_alt` listings for `quattroshapes_pg`. 

``
+++ b/data/101/711/873/101711873.geojson
+    "src:geom_alt":[
+        "quattroshapes_pg",
+        "quattroshapes_pg"
+    ],
```
another:

 ```
+++ b/data/101/712/039/101712039.geojson
+    "src:geom_alt":[
+        "quattroshapes_pg",
+        "quattroshapes_pg"
+    ],
```

Use the metafile I generated in https://gist.github.com/nvkelso/b52e26903a0104e776d2b879778561b0#file-compared-with-master-just-primary-records-txt to fix those, please. Then this PR is ready for merge / PIPing.

I also noted a few followup issues, but don't consider them merge-block:

- #971 Supersede duplicate imported City of X localities into their original representation [USA]
- #973 Supersede duplicate imported localities into their best representation [GLOBAL] 
- #972 Deprecate imported neighbourhoods in our curated cities

**Comment by stepps00** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/pull/824#issuecomment-334621152 was taken care of in  , which removed any duplicate values in the `src:geom_alt` list. 

This PR is ready to process/PIP, so I'll re-assign to @thisisaaronland.

cc @nvkelso - the requested changes should be fixed now.

**Comment by thisisaaronland** [comment]
In the "smaller is not necessary better but it's better than ENORMOUS" department, I've been waiting for about two hours now for the `git show --pretty=format: --name-only 4c711752f3d470ff8d5c952124ba5441cfa4af1e` command to complete and I have no idea when it will.

In the future PRs that invoke the infinity symbol for number of files changed should be avoided.

We're going to have to do this all over again, too, because I am running things in debug mode...

**Comment by thisisaaronland** [comment]
@stepps00 - any idea what's going on here:

```
INFO:root:git show --pretty=format: --name-only 67c8e5c5fdcf6dbea9510f4159f2bad9c4ec516f
INFO:root:git show --pretty=format: --name-only e3d4675a3b51c01e9b196fa75261d4325e8014cd
DEBUG:root:next None
DEBUG:root:checking that /usr/local/data/whosonfirst-data/data/110/897/911/1/1108979111.geojson exists locally
ERROR:root:/usr/local/data/whosonfirst-data/data/110/897/911/1/1108979111.geojson does not exist locally, did you merge the PR?
```

**Comment by nvkelso** [comment]
@thisisaaronland my steps were similar but different, see https://github.com/whosonfirst-data/whosonfirst-data/pull/824#issuecomment-334270474. I didn't run into the problem you report.

**Comment by thisisaaronland** [comment]
@nvkelso the "problem" is in the code - it halts when it can't find a file that's supposed to be on disk (because it's included in the commit list).

**Comment by stepps00** [comment]
@thisisaaronland - checking out the branch to investigate...

**Comment by stepps00** [comment]
There were four commits in this branch that were later "reverted", each listed below:

**qs_pg import - country and dependency**  - https://github.com/whosonfirst-data/whosonfirst-data/pull/824/commits/b297a8b68462df5839b055348e9afed0b7fc0bba
**Revert qs_pg import - country and dependency** - https://github.com/whosonfirst-data/whosonfirst-data/pull/824/commits/ee61c9061f83c870cd3b031cea202cf9f65aa573

**qs_pg import: locality/neighbourhood file** - https://github.com/whosonfirst-data/whosonfirst-data/pull/824/commits/2246e63cbe889ca4fbf8b9678954465df329daf9
**Revert "qs_pg import: locality/neighbourhood file"** - https://github.com/whosonfirst-data/whosonfirst-data/pull/824/commits/aa62812ca4bce818f220f27b3d7967f0ed2c406d

**qs_pg import: county deprecated** - https://github.com/whosonfirst-data/whosonfirst-data/pull/824/commits/697bbf6e0f5d1c2b1a7e4351952b5f9e1e72ce90
**Revert "qs_pg import: county deprecated"** - https://github.com/whosonfirst-data/whosonfirst-data/pull/824/commits/82ac14c806b874a0e5b473038eb518acd7fcbf38

**qs_pg import: locality_funky file** - https://github.com/whosonfirst-data/whosonfirst-data/pull/824/commits/b87ae1243b4a190d2ee70cc565e5d13c0e1b189f
**Revert "qs_pg import: locality_funky file"** - https://github.com/whosonfirst-data/whosonfirst-data/pull/824/commits/b32361533c2419c838f0e8c1c381261757baa56e



The `usr/local/data/whosonfirst-data/data/110/897/911/1/1108979111.geojson` file was added in https://github.com/whosonfirst-data/whosonfirst data/pull/824/commits/b297a8b68462df5839b055348e9afed0b7fc0bba), but removed in https://github.com/whosonfirst-data/whosonfirst-data/pull/824/commits/ee61c9061f83c870cd3b031cea202cf9f65aa573.

**Comment by thisisaaronland** [comment]
Restarted with

```
./tasks/pr-tool.py -d -C -P 824 -X b297a8b68462df5839b055348e9afed0b7fc0bba,ee61c9061f83c870cd3b031cea202cf9f65aa573,2246e63cbe889ca4fbf8b9678954465df329daf9,aa62812ca4bce818f220f27b3d7967f0ed2c406d,697bbf6e0f5d1c2b1a7e4351952b5f9e1e72ce90,82ac14c806b874a0e5b473038eb518acd7fcbf38,b87ae1243b4a190d2ee70cc565e5d13c0e1b189f,b32361533c2419c838f0e8c1c381261757baa56e
```

**Comment by thisisaaronland** [comment]
Of course running this in an Emacs buffer results in Emacs running out of memory and the process being killed...

**Comment by thisisaaronland** [comment]
It stands to reason that trying to create a dictionary containing {INFINITY} files would exhaust all the memory...

```
DEBUG:root:load /usr/local/data/whosonfirst-data/data/421/170/697/421170697.geojson
DEBUG:root:load /usr/local/data/whosonfirst-data/data/421/170/699/421170699.geojson
DEBUG:root:load /usr/local/data/whosonfirst-data/data/421/170/701/421170701.geojson
DEBUG:root:load /usr/local/data/whosonfirst-data/data/421/170/703/421170703.geojson
Segmentation fault (core dumped)
```

**Comment by thisisaaronland** [comment]
Well, the good news is that I am now able to sanity-check all the files before processing them.

The bad news is that because this is a mix of points and other larger placetypes, it will probably take a while to process everything. I am going to let this run in debug mode for a while longer and then just throw caution to the wind...

**Comment by thisisaaronland** [comment]
This is running for real now (I did not wait for the dry-run to complete) so we'll see what happens.

Also @stepps00 note the merge conflicts that have appeared in the interim...

**Comment by stepps00** [comment]
@thisisaaronland - looks like merge conflicts from recent neighbourhood imports. Should the merge conflicts be resolved in a new commit to this branch?

**Comment by nvkelso** [comment]
From IRL: I’m going to work with Stephen to split this PR into two:

- points only new features
- property edits on existing features, and those new features

On Thu, Oct 26, 2017 at 9:59 AM, Aaron Straup Cope <notifications@github.com

**Comment by nvkelso** [comment]
Splitting the PR in two was a dead end. Instead @stepps00 is going to list out the wof:id of the point features added in the following commits that require PIP (essentially the files changed in those PRs filtering out the polygon features):

```
PIP qs_pg import: locality_gp_neighbourhood_gn - 510bbb2  
PIP qs_gp: county cessation files - 5d6b098  
PIP qs_pg import: localadmin - 2139706  
PIP qs_pg import: localities - aa23867  
PIP qs_pg import: neighbourhoods - 8ca83bf  
PIP qs_pg import: locality_funky - 042a215  
```

Then @thisisaaronland will write new logic to just PIP based on that custom list in this original branch. The other features would merge as property only-edits. Huzzah!

**Comment by stepps00** [comment]
List of ids that require PIP work: [points_to_pip_824.txt](https://github.com/whosonfirst-data/whosonfirst-data/files/1420400/points_to_pip_824.txt)

**Comment by thisisaaronland** [comment]
Once more, in to the breach...

**Pull request merged**
