### PR TITLE
Fix wrong hierarchy for Wittenbach (1175611227)

### PR DESCRIPTION
**Pull request by Joxit**
Hi there,
I found a data issue for [Wittenbach](https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/117/561/122/7/1175611227.geojson).
There were a deprecated localadmin in its hierarchy.

This is related to a pelias issue here https://github.com/pelias/pelias/issues/778

### CODE REVIEW

**Comment by missinglink** [comment]
related https://github.com/whosonfirst-data/whosonfirst-data/issues/1377

**Comment by stepps00** [comment]
Thanks @Joxit !

**Comment by nvkelso** [comment]
Closed in favor of https://github.com/whosonfirst-data/whosonfirst-data/pull/1533.

**Comment by Joxit** [comment]
Okay, Thx for the future change

**Comment by nvkelso** [comment]
(Should merge today, more of a book keeping thing where you smashed your changes into another PR to accelerate it.)

**Pull request closed without merging**
