### PR TITLE
Updated record to correct parent, hierarchy, and belongsto fields for HU macroregion

### LINKED ISSUE #250: Dél-Dunántúl is in Hungary but data says country is Europe
This record's country is mis-assigned:

https://whosonfirst.mapzen.com/spelunker/id/404227491

### PR DESCRIPTION
**Pull request by stepps00**
Fixes #250.
- Updated `wof:belongsto`, `wof:hierarchy`, and `wof:parent_id` fields to include [Hungary](https://whosonfirst.mapzen.com/spelunker/id/85633237/#7/47.179/19.484) instead of [Europe](https://whosonfirst.mapzen.com/spelunker/id/102191581/#2/68.2/22.0).
- Exportified to update `geometry` and `geomhash`.

### CODE REVIEW

**Comment by nvkelso** [comment]
LGTM

**Comment by thisisaaronland** [comment]
Holding back for testing with supersedes code since the descendants of this record will need to have their hierarchies updated accordingly.

**Comment by nvkelso** [comment]
@stepps00 Please fix the bad merge in this PR.

**Comment by stepps00** [comment]
Merge has been fixed in this PR - over to @thisisaaronland for import (though this still impacts descendant records).

**Comment by stepps00** [comment]
This work was completed through BI: https://github.com/whosonfirst-data/whosonfirst-data/commit/aae3312fd6a5d9a13bc1b3e9a14ead5d1f0169fc and descendant records do not need updates.

Closing this record.

**Pull request closed without merging**
