### PR TITLE
Updated geometries and alt records for zetashapes neighbourhoods

### PR DESCRIPTION
**Pull request by stepps00**
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/149.

Steps taken to update records for this PR:

- Collected all neighbourhood records with:
  - `src:geom` of `zetashapes`
  - `mz:tier_locality` of `1`, `2`, or `3`
- Removed any records with a `edtf:deprecated` or `edtf:cesstion` date
- Created new alt_geom records with the default (`zetashapes`) geometry and added `zetashapes` to the default record's `src:geom_alt` property
- Removed `quattroshapes` from the `src:alt_geom` property
- Updated default geometry with the alt_geom (quattroshapes) geometry
  - This included updated `lbl` and machine-generated `geom` fields
- Updated `src:geom` property to `quattroshapes`
- Removed all `quattroshapes` alt-geom records
 
Note that this does not include any records with a `tier_locality` value of `NULL`. After reviewing some `NULL` features in QGIS, I'm not convinced all of their geometries should be swapped with the `quattroshapes` alt geometry.

### CODE REVIEW

**Comment by stepps00** [comment]
**To do:**

For all records with a `src:lbl` (or variant) property is `mz`, revert the `lbl:latitude` and `lbl:longitude` values to pre-PR values.

**Comment by stepps00** [comment]
Commit  	f03a31d reverted changes to the `lbl:latitude` and `lbl:longitude` properties. The commit also includes updated `mps:latitude` and `mps:longitude` properties.

**Comment by stepps00** [comment]
@nvkelso - spot checked records on my local branch, this should be ready for review/merge.

**Comment by stepps00** [comment]
Commit  	58f0ea8 fixed merge conflicts for ~5800 records in this branch. After spot-checking it looks like there are no additional updates needed.

**Comment by thisisaaronland** [comment]
@stepps00 this has merge conflicts - would you please fix those and reassign to me.

**Comment by stepps00** [comment]
Last commit fixed merge conflicts, back to @thisisaaronland.

**Comment by thisisaaronland** [comment]
Just posting this here for posterity. This is what Git said when I `merge --no-ff` -ed:

```
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your merge.renamelimit variable to at least 17290 and retry the command.
```

**Comment by thisisaaronland** [comment]
Processing in debug mode. I have no idea how long this will take, but it's got it's own work pony to process things with...

**Pull request merged**
