### PR TITLE
JSON schema validation and WOF document property normalisation

### PR DESCRIPTION
**Pull request by vicchi**
See whosonfirst/whosonfirst-json-schema#1 for details of this PR in context with other changes/pull requests.

### CODE REVIEW

**Comment by stepps00** [comment]
Thanks @vicchi ! I'm going to review the changes in each commit and let you know if I have any questions..

**Comment by vicchi** [comment]
Thanks! Mr Kelso has made a few comments elsewhere that may impact this and I’ll check them tomorrow my time

**Comment by vicchi** [comment]
@stepps00 Have you had a chance to review this PR? I'd really like to get it merged and close down the meta-issue at https://github.com/whosonfirst/whosonfirst-json-schema/issues/1

**Comment by nvkelso** [comment]
I'll take a look for @stepps00 today as he's OOO.

**Comment by nvkelso** [comment]
I'll take a look for @stepps00 today as he's OOO.

**Comment by nvkelso** [comment]
I started working my way thru this and haven't seen any red flags. But it's a BIG PR so I'll continue to look thru it (on the command line, too big for GH.com interface) with Stephen on Monday.

**Comment by nvkelso** [comment]
I started working my way thru this and haven't seen any red flags. But it's a BIG PR so I'll continue to look thru it (on the command line, too big for GH.com interface) with Stephen on Monday.

**Comment by nvkelso** [comment]
I started working my way thru this and haven't seen any red flags. But it's a BIG PR so I'll continue to look thru it (on the command line, too big for GH.com interface) with Stephen on Monday.

**Comment by vicchi** [comment]
@nvkelso I hear you ... and I know it's a lot of work to verify this. But the upside is that there's now data consistency throughout the repo plus the tools to keep this in place.

**Comment by vicchi** [comment]
@nvkelso I hear you ... and I know it's a lot of work to verify this. But the upside is that there's now data consistency throughout the repo plus the tools to keep this in place.

**Comment by nvkelso** [comment]
> Most concordance values changed from string to int, but not all, like fips:code

FIPS codes are strings to preserve the leading `0` (like California is `06` and not `6`).

**Comment by nvkelso** [comment]
> Most meso: property values converted from ints to strings.

Since some of the meso property values need to be strings (even if more are ints), they all have to generically be strings. 🤷‍♂️

**Comment by nvkelso** [comment]
In any event, these all match up with expectations from the properties repo. Let's merge this!

**Comment by nvkelso** [comment]
@thisisaaronland I'm fine with merging this now. It'll mean master will be, well, master but since the SQLite dumps aren't updating then master will be ahead of those (which is okay, they can catch up). Are you fine with us merging it?

**Comment by thisisaaronland** [comment]
Yes, go ahead and merge. If I can't make any meaningful headway on automating builds this weekend I can at least do it (again) by hand which will be useful for documenting the steps and being irritat^H^H^H I mean something to encourage me to finish automating the builds.

But maybe we should make @vicchi writing a long and twisty blog post as a prerequisite for merging to master... ;-)

**Comment by thisisaaronland** [comment]
☝️ I am half-serious about that, BTW...

**Comment by nvkelso** [comment]
🍪for everyone!

**Comment by vicchi** [comment]
@nvkelso I made myself an espresso instead of a cookie!

@thisisaaronland I'm mulling over that blog post right now. The working title is "Implementing JSON schema for WOF for data consistency; or how to take two steps backwards for every step you take forwards". I'm also half serious about that title BTW

**Pull request merged**
