### PR TITLE
Zoom and NE prop updates - continent, country, pop places, regions

### PR DESCRIPTION
**Pull request by stepps00**
~This PR includes newly curated `mz:min_zoom` property values for 5800 of the 7350 records in the `ne_10m_populated_places.shp` file.~

~Features that did not match an existing record in WOF will be imported in a separate PR.~

To do:

- [x] Merge this PR with https://github.com/whosonfirst-data/whosonfirst-data/pull/851
- [x] Import all properties for **matched** features from the `populated_places` file
- [x] Once #660 is merged, update zoom levels for all regions. This should be done on a country-by-country basis with one-offs updated separately (like Moscow example)
- [ ] Take care of merge conflicts

### CODE REVIEW

**Comment by nvkelso** [comment]
@stepps00 Can you fix up the conflicting file, please? Then ready for @thisisaaronland, and only a property merge (no PIPing).

**Comment by stepps00** [comment]
Most recent commit fixed merge conflicts. 

Two additional follow-up PRs incoming: one that includes no-matched features and one that includes new `ne:* properties for records in this branch. 

No PIPing required for this PR.

**Comment by stepps00** [comment]
To do:

- [ ] Import all new `ne:*` properties for these records
- [ ] Fix merge conflicts

**Comment by stepps00** [comment]
This PR now contains all work for the populated_places (localities), regions (continents), marineareas, and countries. 

The only to-do for this PR is run updates for the states (regions) file once the PR for #660 is merged to `master`.

**Comment by stepps00** [comment]
@ndcartography - you've branched off of this branch to conduct some zoom statistics work.

I am working on the `region` placetype; I will add a new commit by tomorrow with additional zoom work at the region level.

**Comment by stepps00** [comment]
The most recent commits import new `min_zoom`, `max_zoom`, and `ne:*` properties (including many new concordances) to records at the region placetype.

At first, there were some funky joins (134 of them) on records with non-region placetypes. These records were reset to their original state and #866 was opened to track bunk `gn:id` concordance values. French regions were updated separately.

New commit to fix merge conflicts incoming...

**Comment by stepps00** [comment]
Closing in favor of... https://github.com/whosonfirst-data/whosonfirst-data/pull/867

**Pull request closed without merging**
