### PR TITLE
DO NOT MERGE YET: update BTV boundary

### PR DESCRIPTION
**Pull request by wboykinm**
# Pull Request Template

Who's On First (WOF) relies on your local knowledge, interest, and expertise to contribute to an ever-improving database of places. 

When submitting a Pull Request (PR) to the `whosonfirst-data` repository, we kindly ask you to use this template in your PR description and replace the website links and Who's on First IDs appropriately:

- **What problem does this address?**
 
 - What did you see in Who's on First?
 
 - What did you expect to see?
 
- **Overview of edits and methodology:**

 - How was the data updated to address the problem?
 
 - How did you perform the edit? (Someone else might want repeat your fix elsewhere, play your fix forward.)

- **Direct link to your source or references** (.shp or .geojson file) that you used for new administrative geometries:

 - _https://www.directlink.gov/file.geojson_

- **Direct link to the open license file** that is associated to that source file:

 - _https://www.directlink.gov/license.txt_
 
- **List of all WOF records that were deprecated:**

 - _012345678, 123456789, 234567890, etc._
 
- **List of all WOF records that were given `supersedes` or `supersedes_by` values:**

 - _012345678, 123456789, 234567890, etc._
 
- **List of all WOF records that changed `placetype`:**

 - _012345678, 123456789, 234567890, etc._
 
- **List of all WOF records that were updated in any way, shape, or form:**

  - _012345678, 123456789, 234567890, etc._

### CODE REVIEW

**Comment by wboykinm** [comment]
Working on #434

**Comment by nvkelso** [comment]
Anything we can help with, @wboykinm?

**Comment by wboykinm** [comment]
@nvkelso Heh. Find me a clone.

**Comment by wboykinm** [comment]
This got stale. I'm going to close and start over.

**Pull request closed without merging**
