### PR TITLE
Array nesting

### PR DESCRIPTION
**Pull request by missinglink**
Fix nested array

### CODE REVIEW

**Comment by missinglink** [comment]
Is this something I can do from a patch inside GitHub or do I need a local checkout?

**Comment by nvkelso** [comment]
Exportify is General WOF tool, you could run it on local copy of file and then paste into github.com and we’d be fine. Checkout is “better”, but takes a while these days. Stephen is OOO this week.

**Comment by thisisaaronland** [comment]
Tangentially related, but still not ready to replace the `wof-exportify` Python tool (and it's small universe of dependencies is this:

https://github.com/whosonfirst/go-whosonfirst-export

**Comment by stepps00** [comment]
Replaced with #1601. Going forward, the plan is to commit to per-country repos.

**Pull request closed without merging**
