### PR TITLE
Updated Portland, OR neighbourhood records

### LINKED ISSUE #459: Merge Downtown and Jefferson Street neighbourhood records in Portland, OR
In response to an [external PR](https://github.com/whosonfirst-data/whosonfirst-data/pull/454), we need a quick-fix for the [Jefferson Street](https://whosonfirst.mapzen.com/spelunker/id/85868953/#15/45.5204/-122.6745) and [Downtown](https://whosonfirst.mapzen.com/spelunker/id/85867131/#14/45.5125/-122.6780) neighbourhood records in Portland, OR. Open a new PR that includes the following:
- Create a new Downtown record that is a copy of the old Downtown record (and all it's properties), adding in the additional shape geometry from this weird Jefferson record (almost doubling Downtown's size). 
- Supersede both old Downtown and Jefferson into the new Downtown
- Mark Jefferson as deprecated since it seems to just be junk.

### PR DESCRIPTION
**Pull request by stepps00**
Fixes #459.

This PR includes the following:
- Creates a new Downtown record that is a copy of the old Downtown record (and all it's properties), adding in the additional shape geometry from this weird Jefferson record (almost doubling Downtown's size). 
- Supersedes both old Downtown and Jefferson into the new Downtown
- Marks Jefferson as deprecated since it seems to just be junk.

### CODE REVIEW

**Comment by nvkelso** [comment]
LGTM.

I think this involves re-PIP'ing venues?

**Comment by nvkelso** [comment]
@thisisaaronland This PR is in response to a developer correction request from Portland.

**Comment by stepps00** [comment]
@nvkelso [the descendants of Downtown](https://whosonfirst.mapzen.com/spelunker/id/85868953/descendants/?exclude=nullisland#16/45.5210/-122.6770) and [the descendants of Jefferson Street](https://whosonfirst.mapzen.com/spelunker/id/85868953/descendants/?exclude=nullisland#16/45.5210/-122.6770) will need to updated to include the new Downtown neighbourhood in their hierarchy (and remove the existing neighbourhood).

**Comment by thisisaaronland** [comment]
@stepps00 - what is the relationship between this PR and https://github.com/whosonfirst-data/whosonfirst-data/issues/391?

Can this one be closed?

**Comment by stepps00** [comment]
@thisisaaronland - closing this PR. Verified that issue #459 has been fixed via the Portland neighbourhood updates.

**Pull request closed without merging**
