### PR TITLE
Backfilled mps: properties 

### PR DESCRIPTION
**Pull request by stepps00**
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/945.

For any `neighbourhood`, `microhood`, `macrohood`, `campus`, `locality`, or `borough` records updated through the neighbourhood update work, new `mps:latitude` and `mps:longitude` properties have been added.

These properties have been populated using the `reversegeo:latitude` and `reversegeo:longitude` properties.

Script: https://github.com/mapzen/whosonfirst-toolbox/blob/master/scripts/issue-945-backfill-lat-long-props.py

### CODE REVIEW

**Comment by nvkelso** [comment]
@stepps00 you might as well test for not "mz:is_current" or "mz:is_current":-1 and set those to 1 at the same time (leaving "mz:is_current":0, alone)?

**Comment by nvkelso** [comment]
Otherwise LGTM.

**Comment by stepps00** [comment]
Re https://github.com/whosonfirst-data/whosonfirst-data/pull/970#issuecomment-334573554: we have https://github.com/whosonfirst-data/whosonfirst-data/issues/951 open for that specific issue, but it seems easier to crank this all out in a single PR since I have the `wof:id` values.

**Comment by stepps00** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/pull/970/commits/bbbde6ab7587a8ddf609d879e002db3143df13f5 ensures that any updated record in this PR that **was not** already tagged with `mz:is_current:0` was tagged with `mz:is_current:1`

**Pull request merged**
