### PR TITLE
Updated duplicate Pago-Pago records in American Samoa

### PR DESCRIPTION
**Pull request by stepps00**
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/448.
- Superseded the Pago Pago point record into the Pago Pago record with a geometry
- Brought over concordances and hierarchy information from superseded record
- Updated `iso:country` and added `iso:parent` field to correct record, as this is a dependency
- Added US id to the `parent_id` field
- Exportified
- Deprecated and added `mz:is_current` field to point record, as this was never a valid record to begin with

### CODE REVIEW

**Comment by stepps00** [comment]
Also, no descendants under either of these records, so no hierarchy rebuilding necessary.

**Comment by nvkelso** [comment]
LGTM, over to @thisisaaronland

**Comment by nvkelso** [comment]
No PIPing, can merge directly.

**Comment by stepps00** [comment]
Closing this PR because these changes were made through Boundary Issues (https://github.com/whosonfirst-data/whosonfirst-data/commit/62e643aefee7a7491474d68ce7792471d3d4702a).

**Pull request closed without merging**
