### PR TITLE
Reworked harvested statoids props

### PR DESCRIPTION
**Pull request by stepps00**
New Statoids property updates.

### CODE REVIEW

**Comment by nvkelso** [comment]
Please switch to `_` for `stations:as-of-date` (to: `stations:as_of_date`).

**Comment by nvkelso** [comment]
Other than that, looks good to me :)

**Comment by stepps00** [comment]
The most recent commit switches `statoids:as-of-date` to `statoids:as_of_date`.

List of all updated records in this PR [here](https://github.com/whosonfirst-data/whosonfirst-data/files/1304901/files-in-pr.copy.txt).

**Comment by stepps00** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/pull/943#pullrequestreview-69724360 fixed in 7a7abb1.

**Pull request merged**
