### PR TITLE
US: Move all mobile home localities in US to campus

### LINKED ISSUE #1431: Some new GeoNames locality records should be campuses
Some of the `PPL` GeoNames placetype records introduced recently as locality records should actually be campus records, specifically any "Mobile Home" or "Mobile Home Park" records.

Poke around and find other inconsistencies and note them here.

### PR DESCRIPTION
**Pull request by stepps00**
Fixes #1431.

Deprecates any locality in the US sourced from GeoNames with "Mobile Home Park" in the name, and supersedes it to a new campus record.

This will not require PIP work, can be merged as-is.

### CODE REVIEW

**Comment by nvkelso** [comment]
@stepps00 is there any additional work for this, like for `Trailer Park` or other name variants?

**Comment by stepps00** [comment]
@nvkelso -- good question.. I'll look at other localities in the metafile and note additional variants here.

**Comment by stepps00** [comment]
There are ~750 additional records that I'm going to rework in an upcoming commit.
I checked for the following strings (upper and lower case): "Trailer Park", "Campsite", "Campground", "RV Park", "Caravan Park".

**Comment by missinglink** [comment]
Hey @stepps00, I just noticed that https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/132/714/557/3/1327145573.geojson is classified as a locality, is that correct?

**Comment by stepps00** [comment]
@missinglink - that [record](https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/132/714/557/3/1327145573.geojson) is a deprecated locality that was taken care of in this PR and moved into a new [campus record](https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/137/690/980/7/1376909807.geojson).

A small percentage of GeoNames locality points that were imported (like these mobile home parks) should actually be campus records, this PR should fix any mobile home or related case, moving place to a new campus record.

**Pull request merged**
