### PR TITLE
Reversegeo polygon for nigeria, pointer props

### PR DESCRIPTION
**Pull request by stepps00**
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/960.

- New `reversegeo:geometry` ~~`reversegeo:polygon`~~ property for the country record of Nigeria
- New mapzen-sourced reversegeo record for Nigeria

### CODE REVIEW

**Comment by nvkelso** [comment]
We should probably fully PIP this again since the coastal polygon has issues before that people complained about (more than just Lagos).

**Comment by stepps00** [comment]
Last commit includes PIP work for all records in Nigeria. Will merge shortly.

**Comment by stepps00** [comment]
@nvkelso - OK to merge?

**Comment by nvkelso** [comment]
Yep

**Pull request merged**
