### PR TITLE
Second round of geonames names import

### PR DESCRIPTION
**Pull request by stepps00**
Using https://github.com/mapzen/whosonfirst-toolbox/blob/master/scripts/create_gn_id_list.py, a new csv file was created that contained every `gn:id` concordance value in WOF, and the record's `wof:id`. 

Using that list, the geonames import script was run a second time against the `alternamenames.tsv` file, which caught and added new `name:*` properties to an additional 2,410 records.

Follows https://github.com/whosonfirst-data/whosonfirst-data/pull/874.

### CODE REVIEW

**Comment by stepps00** [comment]
To do: 

- [ ] Add names and `gn:id` concordance for `marinearea`, `disputed`, and `dependency` records that @ndcartography reviewed.

**Comment by nvkelso** [comment]
So far with the first set of 2140 features everything is looking good. I see the right names being added, and even abbreviations :)

**Comment by nvkelso** [comment]
Regarding https://github.com/whosonfirst-data/whosonfirst-data/pull/884#issuecomment-320320846, we talked IRL and @stepps00 will work with @ndcartography on a followup PR for those stragglers.

**Comment by stepps00** [comment]
This PR is being processed through the Boundary Issue pipeline tool (woo!), here: https://whosonfirst.mapzen.com/boundaryissues/pipeline/234/

I'll open a new PR to track https://github.com/whosonfirst-data/whosonfirst-data/pull/884#issuecomment-320320846 shortly.

**Pull request merged**
