### PR TITLE
Updated X-Mas Island and Indian Ocean Territories

### LINKED ISSUE #8: Christmas Island isn't a dependency
wof_id  iso name    parent_id
85632497    CX  Christmas Island    85632793
data/856/324/97/85632497.geojson

Instead it should be listed as a region of 
85632495 Indian Ocean Territories

### PR DESCRIPTION
**Pull request by stepps00**
Fixes #8.

The following work was completed in this PR:
- Deprecated the current Christmas Island _dependency_ record and superseded it to a new Christmas Island _region_ record
- Created a new Christmas Island region record with a new `wof:id` (placetype change was a significant event, so it required a new record/id)
- Updated `wof:hierarchy` and `parent_id` to replace Australia's `wof:id` with Indian Oceans Territories' `wof:id`
- Updated Indian Ocean Territories' `geometry` to include Christmas Island

### CODE REVIEW

**Comment by nvkelso** [comment]
LGTM

**Comment by nvkelso** [comment]
Back to @stepps00 to fix merge conflict.

**Comment by stepps00** [comment]
Most recent commit (9e2e406) fixes merge conflict.

**Comment by nvkelso** [comment]
Back to @thisisaaronland

**Pull request merged**
