### PR TITLE
France: Swap out fra-odp geometries with centroid points

### PR DESCRIPTION
**Pull request by stepps00**
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/1204.

Swaps the neighbourhood polygon geometries (`fra-odp`-sourced) for a Mapshaper-sourced point geometry.

Geometries and centroids, as displayed in QGIS:

screen shot 2018-10-02 at 12 43 25 pm

### CODE REVIEW

**Comment by nvkelso** [comment]
Nice! For the places that had a quattroshapes polygon before let's also please restore that as the default polygon shape.

**Comment by stepps00** [comment]
Last three commits take care of geometry swapping and property clean-up, per https://github.com/whosonfirst-data/whosonfirst-data/pull/1333#issuecomment-426408998.

**Comment by nvkelso** [comment]
@stepps00 Can you add a screenshot of what the new geometries look like, please? I'm expecting to see lots of popcorn and some chia seeds.

**Comment by stepps00** [comment]
screen shot 2018-10-02 at 1 26 51 pm

Green shapes are the Quattroshapes geometries.

**Comment by stepps00** [comment]
Related: https://github.com/whosonfirst/whosonfirst-sources/issues/117

**Comment by nvkelso** [comment]
This looks good, but please also control the parent_id and hierarchy for the `micorhoods` so they don't get corrupted / need PIPing to now poor polygons.

**Pull request merged**
