### PR TITLE
Various: Update NE country geometries

### PR DESCRIPTION
**Pull request by stepps00**
WIP. 

To do:
- [x] Move existing Natural Earth geometries to alt-geometry file
- [x] Dissolve existing child record geometries to create new `whosonfirst` geometry for each country
- [x] Use src via property when necessary (and catalogue in properties repo)
- [x] Fill in all holes and remove all extra nodes after dissolving geometries
- [x] Validate all geometries
- [x] Verify all `src:geom` and `src:geom_alt` properties contain correct values
- [x] Ensure all new geometries are simplified down to ~3mb in size

### CODE REVIEW

**Comment by stepps00** [comment]
New source used for a handful of country geometries: https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/us-dshiu.json

**Comment by nvkelso** [comment]
For: https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/1fd727e5c5f4d01712ef5c8be903039f84e38e79/data/856/322/03/85632203.geojson

- keep: "src:geom_via":"quattroshapes",
- kill: "src:via":"quattroshapes",

**Comment by nvkelso** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/blob/1fd727e5c5f4d01712ef5c8be903039f84e38e79/data/856/338/05/85633805.geojson

Make sure Ukraine and Russia reflect defacto state of things (Crimea needs to be swapped).

**Comment by nvkelso** [comment]
Some island rich countries could stand a rev-geo shape that's more expansive, but there are other issue that cover that already:

- https://github.com/whosonfirst-data/whosonfirst-data/blob/1fd727e5c5f4d01712ef5c8be903039f84e38e79/data/856/333/41/85633341.geojson

**Comment by nvkelso** [comment]
The country of Finland shouldn't include dependency shape of Aland, split those out:

- https://github.com/whosonfirst-data/whosonfirst-data/blob/1fd727e5c5f4d01712ef5c8be903039f84e38e79/data/856/331/43/85633143.geojson
- https://spelunker.whosonfirst.org/id/85632789/

**Comment by nvkelso** [comment]
See if you can get better Monte Carlo shape from France?

- https://github.com/whosonfirst-data/whosonfirst-data/blob/1fd727e5c5f4d01712ef5c8be903039f84e38e79/data/856/332/85/85633285.geojson

**Comment by nvkelso** [comment]
Other than that looks good!

**Comment by stepps00** [comment]
39cf042 - Completes the work around Crimea work and removes `src:via`

**Comment by stepps00** [comment]
f50615d - Removes Aland from the Finland country geometry.

**Comment by stepps00** [comment]
f5190f5 - Adds a new geometry to Monaco

**Comment by nvkelso** [comment]
Aland still has a generic shape, but everything else is good here :)

**Pull request merged**
