### PR TITLE
NE min_zoom and property updates

### PR DESCRIPTION
**Pull request by stepps00**
Replaces https://github.com/whosonfirst-data/whosonfirst-data/pull/846.

This PR includes the following updates:

- New min and max zoom values for `admin0`, `states_provinces_lakes`, `marine_polys`, and `populated_places` files
- New `ne:*` properties for `admin0`, `states_provinces_lakes`, `marine_polys`, and `populated_places` files
- Takes care of any merge conflicts 
- New non-matched ne point records (localities)

Requires PIP work.

This provides data for the Spelunker's planned `mz:min_zoom` and `mz:max_zoom` range filters: https://github.com/whosonfirst/whosonfirst-www-spelunker/issues/107

### CODE REVIEW

**Comment by stepps00** [comment]
@nvkelso - this branch is ready for review. It replaces the branch that had merge conflicts and includes the cherry-picked commits that we reviewed by hand.

Commit https://github.com/whosonfirst-data/whosonfirst-data/pull/867/commits/93f1ca9ebf5ea08313f452f2b21e504ee6206cc5 _does_ include a few new records (roughly 2500 new records), so this PR will require PIP work.

**Comment by nvkelso** [comment]
Where _infinite_ files changed is actually only **12k** files, which lines up with my expectations:

- `git diff --name-status HEAD 14e3b0e92674a09e49b35bf2e31dbf9c161bc237 > ~/tmp/files-in-pr.csv`
- https://gist.github.com/nvkelso/4463ad79b2e2df5eb95d3f6f16d080f2

And reviewing those 12k files on the command line can be done with:

- `git diff HEAD 14e3b0e92674a09e49b35bf2e31dbf9c161bc237`

**Comment by nvkelso** [comment]
**By placetype:**

- [ ] continent
- [ ] ocean
- [ ] marinearea
- [ ] country
- [ ] dependency
- [x] region
- [ ] locality
    - [x] updates
    - [ ] new records

Need **country**, **marinearea**, and **continents** need work. Missing commit during merge conflict resolution? 

**By property edits:**

- [x] mz:min_zoom
- [x] mz:max_zoom
- [x] ne:*
- [x] concordances
- [x] Natural Earth alt geoms

I correctly see `mz:min_zoom` being added:

```
diff --git a/data/101/712/003/101712003.geojson b/data/101/712/003/101712003.geojson
index 0a50c3b..fc5fc80 100644
--- a/data/101/712/003/101712003.geojson
+++ b/data/101/712/003/101712003.geojson
@@ -15,6 +15,7 @@
     "mps:latitude":40.741446,
     "mps:longitude":-84.108085,
     "mz:hierarchy_label":1,
+    "mz:min_zoom":6.7,
     "name:ara_x_preferred":[
         "\u0644\u064a\u0645\u0627"
     ],
```

I correctly see `ne:*` properties being added:

```
diff --git a/data/101/712/003/101712003.geojson b/data/101/712/003/101712003.geojson
index 0a50c3b..fc5fc80 100644
--- a/data/101/712/003/101712003.geojson
+++ b/data/101/712/003/101712003.geojson
@@ -96,6 +97,98 @@
     "name:war_x_preferred":[
         "Lima"
     ],
+    "ne:ADM0CAP":0.0,
+    "ne:ADM0NAME":"United States of America",
+    "ne:ADM0_A3":"USA",
+    "ne:ADM1NAME":"Ohio",
+    "ne:ADMIN1_COD":0.0,
+    "ne:CAPALT":0.0,
+    "ne:CAPIN":null,
+    "ne:CHANGED":0.0,
+    "ne:CHECKME":0,
+    "ne:CITYALT":null,
+    "ne:COMPARE":0,
+    "ne:DIFFASCII":0,
+    "ne:DIFFNOTE":null,
+    "ne:ELEVATION":268.0,
+    "ne:FEATURECLA":"Populated place",
+    "ne:FEATURE_CL":"P",
+    "ne:FEATURE_CO":"PPL",
+    "ne:GEONAMEID":5160783.0,
+    "ne:GEONAMESNO":"Geonames ascii name + lat.d + long.d matching.",
+    "ne:GN_ASCII":"Lima",
+    "ne:GN_POP":39906.0,
+    "ne:GTOPO30":258.0,
+    "ne:ISO_A2":"US",
+    "ne:LABELRANK":1,
+    "ne:LATITUDE":40.742874,
+    "ne:LONGITUDE":-84.105265,
+    "ne:LS_MATCH":1,
+    "ne:LS_NAME":"Lima1",
+    "ne:MAX_AREAKM":87.0,
+    "ne:MAX_AREAMI":33.0,
+    "ne:MAX_BBXMAX":-84.016667,
+    "ne:MAX_BBXMIN":-84.208333,
+    "ne:MAX_BBYMAX":40.791667,
+    "ne:MAX_BBYMIN":40.683333,
+    "ne:MAX_NATSCA":20.0,
+    "ne:MAX_PERKM":100.0,
+    "ne:MAX_PERMI":62.0,
+    "ne:MAX_POP10":68364.0,
+    "ne:MAX_POP20":68364.0,
+    "ne:MAX_POP300":0.0,
+    "ne:MAX_POP310":0.0,
+    "ne:MAX_POP50":0.0,
+    "ne:MEAN_BBXC":-84.123277,
+    "ne:MEAN_BBYC":40.74245,
+    "ne:MEGACITY":0,
+    "ne:MEGANAME":null,
+    "ne:MIN_AREAKM":87.0,
+    "ne:MIN_AREAMI":33.0,
+    "ne:MIN_BBXMAX":-84.016667,
+    "ne:MIN_BBXMIN":-84.208333,
+    "ne:MIN_BBYMAX":40.791667,
+    "ne:MIN_BBYMIN":40.683333,
+    "ne:MIN_PERKM":100.0,
+    "ne:MIN_PERMI":62.0,
+    "ne:NAME":"Lima",
+    "ne:NAMEALT":null,
+    "ne:NAMEASCII":"Lima",
+    "ne:NAMEDIFF":0,
+    "ne:NAMEPAR":null,
+    "ne:NATSCALE":20,
+    "ne:NOTE":null,
+    "ne:POP1950":0.0,
+    "ne:POP1955":0.0,
+    "ne:POP1960":0.0,
+    "ne:POP1965":0.0,
+    "ne:POP1970":0.0,
+    "ne:POP1975":0.0,
+    "ne:POP1980":0.0,
+    "ne:POP1985":0.0,
+    "ne:POP1990":0.0,
+    "ne:POP1995":0.0,
+    "ne:POP2000":0.0,
+    "ne:POP2005":0.0,
+    "ne:POP2010":0.0,
+    "ne:POP2015":0.0,
+    "ne:POP2020":0.0,
+    "ne:POP2025":0.0,
+    "ne:POP2050":0.0,
+    "ne:POP_MAX":68364,
+    "ne:POP_MIN":39906,
+    "ne:POP_OTHER":6068380,
+    "ne:RANK_MAX":8,
+    "ne:RANK_MIN":7,
+    "ne:SCALERANK":7,
+    "ne:SOV0NAME":"United States",
+    "ne:SOV_A3":"USA",
+    "ne:TIMEZONE":"America/New_York",
+    "ne:UN_ADM0":null,
+    "ne:UN_FID":0,
+    "ne:UN_LAT":0.0,
+    "ne:UN_LONG":0.0,
+    "ne:WORLDCITY":0.0,
     "qs:a0":"United States",
     "qs:a1":"*Ohio",
     "qs:a1_lc":"39",
@@ -134,7 +227,7 @@
         "wk:page":"Lima, Ohio"
     },
     "wof:country":"US",
-    "wof:geomhash":"fcefa108871b7b81716fa0d73fe35e03",
+    "wof:geomhash":"d76bb31c0ae2478530efe6e8b70394f1",
     "wof:hierarchy":[
         {
             "continent_id":102191575,
@@ -146,7 +239,7 @@
         }
     ],
     "wof:id":101712003,
-    "wof:lastmodified":1479659648,
+    "wof:lastmodified":1500068922,
     "wof:megacity":"0",
     "wof:name":"Lima",
     "wof:parent_id":404523541,
```

I correctly see concordances being added:

```
"wof:concordances":{
-        "gp:id":"20069858"
+        "fips:code":"",
+        "gn:id":"7602006",
+        "gp:id":"20069858",
+        "hasc:id":"GL.VG"
     },
```

I correctly see Natural Earth alt geoms being added:

```
diff --git a/data/859/154/75/85915475-alt-naturalearth.geojson b/data/859/154/75/85915475-alt-naturalearth.geojson
new file mode 100644
index 0000000..fdd764d
--- /dev/null
+++ b/data/859/154/75/85915475-alt-naturalearth.geojson
@@ -0,0 +1,16 @@
+{
+  "id": 85915475,
+  "type": "Feature",
+  "properties": {
+    "src:geom":"naturalearth",
+    "wof:geomhash":"9db24b90b553791535141a0b8b87b822",
+    "wof:id":85915475
+},
+  "bbox": [
+    -171.7310787374532,
+    63.77971030593568,
+    -171.7310787374532,
+    63.77971030593568
+],
+  "geometry": {"coordinates":[-171.7310787374532,63.77971030593568],"type":"Point"}
+}
\ No newline at end of file
diff --git a/data/859/154/75/85915475.geojson b/data/859/154/75/85915475.geojson
index 17d90dce..aec56b2 100644
--- a/data/859/154/75/85915475.geojson
+++ b/data/859/154/75/85915475.geojson
@@ -18,6 +18,7 @@
     "mps:latitude":63.761297,
     "mps:longitude":-171.717375,
     "mz:hierarchy_label":1,
+    "mz:min_zoom":6.0,
...
     "src:geom":"quattroshapes",
-    "src:geom_alt":[],
+    "src:geom_alt":[
+        "naturalearth"
+    ],
     "wof:name":"Gambell",
     "wof:parent_id":102081401,
     "wof:placetype":"locality",
```

Here's a **region**:

```
diff --git a/data/856/741/47/85674147.geojson b/data/856/741/47/85674147.geojson
index f52d48b..38b8281 100644
--- a/data/856/741/47/85674147.geojson
+++ b/data/856/741/47/85674147.geojson
@@ -19,6 +19,8 @@
     "mps:latitude":40.99255,
     "mps:longitude":20.99013,
     "mz:hierarchy_label":1,
+    "mz:max_zoom":"11.0",
+    "mz:min_zoom":"10.0",
     "name:eng_x_preferred":[
         "Resen Municipality"
     ],
@@ -28,6 +30,64 @@
     "name:und_x_variant":[
         "Opstina Resen"
     ],
+    "ne:abbrev":"",
+    "ne:adm0_a3":"MKD",
+    "ne:adm0_label":"5",
+    "ne:adm0_sr":"1",
+    "ne:adm1_cod_1":"MKD-2894",
+    "ne:adm1_code":"MKD-2894",
+    "ne:admin":"Macedonia",
+    "ne:area_sqkm":"0.00000000000",
+    "ne:check_me":"11",
+    "ne:code_hasc":"MK.RE",
+    "ne:code_local":"",
+    "ne:datarank":"8",
+    "ne:diss_me":"2894",
+    "ne:featurecla":"Admin-1 scale rank",
+    "ne:fips":"MK86",
+    "ne:fips_alt":"",
+    "ne:gadm_level":"1",
+    "ne:geonunit":"Macedonia",
+    "ne:gn_a1_code":"MK.86",
+    "ne:gn_id":"786339",
+    "ne:gn_level":"1",
+    "ne:gn_name":"Opstina Resen",
+    "ne:gn_region":"",
+    "ne:gns_adm1":"MK86",
+    "ne:gns_id":"-94289",
+    "ne:gns_lang":"mkd",
+    "ne:gns_level":"1",
+    "ne:gns_name":"Resen, Opstina",
+    "ne:gns_region":"",
+    "ne:gu_a3":"MKD",
+    "ne:hasc_maybe":"",
+    "ne:iso_3166_2":"MK-",
+    "ne:iso_a2":"MK",
+    "ne:labelrank":"10",
+    "ne:latitude":"41.02700000000",
+    "ne:longitude":"21.04720000000",
+    "ne:mapcolor13":"3",
+    "ne:mapcolor9":"7",
+    "ne:name":"Resen",
+    "ne:name_alt":"",
+    "ne:name_len":"5",
+    "ne:name_local":"",
+    "ne:note":"",
+    "ne:postal":"RE",
+    "ne:provnum_ne":"20037",
+    "ne:region":"Southwestern",
+    "ne:region_cod":"",
+    "ne:region_sub":"",
+    "ne:sameascity":"-99",
+    "ne:scalerank":"10",
+    "ne:sov_a3":"MKD",
+    "ne:sub_code":"",
+    "ne:type":"Statistical Region",
+    "ne:type_en":"Statistical Region",
+    "ne:wikipedia":"",
+    "ne:woe_id":"24550855",
+    "ne:woe_label":"Resen Municipality, MK, Macedonia",
+    "ne:woe_name":"Resen Municipality",
     "qs:a0":"Macedonia",
     "qs:a0_lc":"MK",
     "qs:a1":"Resen",
@@ -51,6 +111,7 @@
     ],
     "wof:breaches":[],
     "wof:concordances":{
+        "fips:code":"MK86",
         "gn:id":786339,
         "gp:id":24550855,
         "hasc:id":"MK.RE",
@@ -59,7 +120,7 @@
         "wk:page":"Resen Municipality"
     },
     "wof:country":"MK",
-    "wof:geomhash":"0e503e9a03e3c2934b32fe808e17650b",
+    "wof:geomhash":"b212fcca637a7b844c8a29b1f415bbd7",
     "wof:hierarchy":[
         {
             "continent_id":102191581,
@@ -71,7 +132,7 @@
     "wof:lang":[
         "unk"
     ],
-    "wof:lastmodified":1485457363,
+    "wof:lastmodified":1500580259,
     "wof:name":"Resen",
     "wof:parent_id":85632373,
     "wof:placetype":"region",
@@ -85,7 +146,7 @@
     20.82907149999977,
     40.85468299999985,
     21.25547549999979,
-    41.215005999999846
+    41.21500599999985
 ],
```

**Comment by nvkelso** [comment]
Cherry picked in commits resolve all placetype examples above! Well, `data/890/531/859/890531859.geojson` is missing a max_zoom, but shrug?

Over to @stepps00 to exportify all these suckers to validate I didn't leave in any git merge cruft.

**Comment by nvkelso** [comment]
Now we're at: https://gist.github.com/nvkelso/4463ad79b2e2df5eb95d3f6f16d080f2

Files there list the changes in the last 5 commits, and then the legit commit on the 20th has the regions (last Thursday).

**Comment by nvkelso** [comment]
Note that the latest meta file for regions says we should have 4964 count, but we only have 4169 in a7897c9f2ddda62d24c76d29b5a77791d93899e5, which leaves 795 which can be derived from the mean of `mz:min_zoom`, `mz:max_zoom` of other regions in the country it's parented by.

**Comment by nvkelso** [comment]
@stepps00 I've reviewed the region min_zoom and max_zoom and created a CSV with 947 features to set (a few more over 795 are made up from manual review and polish). **Please add a new commit** which sets these `mz:min_zoom` and `mz:max_zoom` values onto the specified wof:id features.

- https://gist.github.com/nvkelso/4463ad79b2e2df5eb95d3f6f16d080f2#file-final_948_region_zoom_changes-csv

All features with min_zoom:

screen shot 2017-07-28 at 00 13 03

The 795 missing features (but more were edited):

screen shot 2017-07-27 at 23 16 58

Final counts per min_zoom:

screen shot 2017-07-28 at 00 20 32

**Comment by nvkelso** [comment]
I've removed the NEW files added in 7dc64158667bfcbb3c981335f785c8d5f712ed30 with 333172225565d26ce71eb2ea7e1eaa1edb1343da and moved them to a new branch tracked with PR https://github.com/whosonfirst-data/whosonfirst-data/pull/876.

This PR should now be **property edits only**.

**Comment by nvkelso** [comment]
Doing another round of QA, I've found a partial run of incorrectly added features buried in one of the cherry pick commits (1011 features that are partial dups of what were successfully added in https://github.com/whosonfirst-data/whosonfirst-data/commit/7dc64158667bfcbb3c981335f785c8d5f712ed30):

`git diff --name-status origin/master 333172225565d26ce71eb2ea7e1eaa1edb1343da`

Examples:

```
A	data/114/193/558/7/1141935587.geojson
A	data/114/193/558/9/1141935589.geojson
A	data/114/193/559/1/1141935591.geojson
```

I've removed them with: bd586ce7ceaf180e9e3e72e5f462f9a2e989c5e1.

Rerunning:

`git diff --name-status origin/master bd586ce7ceaf180e9e3e72e5f462f9a2e989c5e1`

Yields no new features (good), but does include 541 more alt geoms for existing features (which don't require PIPing).

**Comment by nvkelso** [comment]
I've verified the original test set in https://github.com/whosonfirst-data/whosonfirst-data/pull/867#issuecomment-318509735 again.

Over to @thisisaaronland for merging. 

- Property only edits (no PIPing)
- **12,453 files** (11922 modified and 531 that receive alt geoms from Natural Earth)
- 19 metafiles are listed as modified (but Stephen didn't modify them). I think you update those anyhow during integration so leaving them as-is for you to sort out.

**Comment by stepps00** [comment]
Note: https://github.com/whosonfirst-data/whosonfirst-data/pull/867#issuecomment-318581170 needs to be complete, then this PR is ready to go.

**Comment by nvkelso** [comment]
I've created a new issue to track the work @stepps00 flagged: https://github.com/whosonfirst-data/whosonfirst-data/issues/877.

**Pull request merged**
