### PR TITLE
Updates to wof:country code, replaces outdated PR

### PR DESCRIPTION
**Pull request by stepps00**
Replaces PR https://github.com/whosonfirst-data/whosonfirst-data/pull/437

Fixes Issue #436.

Updated four records in Puerto Rico with the following:
- `wof:country` changed from `US` to `PR`
- `lastmodified` date updated to reflect date of change via Exportify

### CODE REVIEW

**Comment by nvkelso** [comment]
Changes look good to me. 

Seems to be ready to merge, except meta files aren't updated with the new country code in this PR. @thisisaaronland for that.

**Comment by thisisaaronland** [comment]
Remember `wof:country` is not the same as `iso:country` – and Puerto Rico is a dependency of the US.

I am not opposed to modifying the meaning of `wof:country` to include dependencies but the WOF country label specifically because ISO assigns country code to things that are not.

**Comment by stepps00** [comment]
Only the `wof:country` attributes were changed in this PR (as they were in the original PR) to match the other Puerto Rican features in WoF. The `iso:country` attribute field remained unchanged, as this is an iso-specific value. 

`iso:country` is still `US` and the hierarchy of these four records includes a `dependency_id`. Should we leave the `wof:country` id as-is and add another attribute to signify that these records are part of a dependency?

**Comment by thisisaaronland** [comment]
`wof:country` should be "US" because the United States is the relevant country. `iso:country` should be whatever ISO thinks it is.

**Comment by stepps00** [comment]
@thisisaaronland Puerto Rico has [78 descendant county records](https://whosonfirst.mapzen.com/spelunker/id/85687331/descendants/?exclude=nullisland&placetype=county#9/18.2228/-66.7570). Four of those records (the records in this pull request) have a `wof:country` = `US`, the other 74 records have a `wof:country` = `PR`.

Instead of editing these four records, we should actually be editing the 74 records that have a `wof:country` = `PR`, correct?

Also, I will likely hold off on this issue until https://github.com/whosonfirst-data/whosonfirst-data/pull/484 lands.

**Comment by nvkelso** [comment]
Looks like #484 has been merged, this is ready to action.

**Comment by stepps00** [comment]
Most recent commit (8c12828) fixes merge conflicts.

**Pull request merged**
