### PR TITLE
Removed North America as Country in hierarchy

### LINKED ISSUE #15: Promote Serranilla Bank to disputed (from region of -1)
wof_id	iso	name
85681363	XX	Serranilla Bank

data/102/191/575102191575.geojson

parent now: 
-1
proposed parent:
102191575

### PR DESCRIPTION
**Pull request by stepps00**
Fixes #15.

Removed North America (`102191575`) from Serranilla Bank's `wof:hierarchy`.

### CODE REVIEW

**Comment by nvkelso** [comment]
LGTM, but was exportify run on this? I expected the modified date to change.

**Comment by stepps00** [comment]
Exportified in [most recent commit](7326746)

**Comment by nvkelso** [comment]
LGTM

**Comment by thisisaaronland** [comment]
Does this not have a country of its own? How is it a region, if not?

**Comment by stepps00** [comment]
Updated the record for Serranilla Bank so it now reflects what other disputed territory records look like (see: [Bajo Nuevo Bank](https://whosonfirst.mapzen.com/spelunker/id/85632563/#12/15.8243/-79.8653))

* Updated `placetype` to `disputed`.
* Added hierarchy for all countries that claim ownership (Colombia, United States, Nicaragua, Honduras).
* Exportified.
* Updated `belongsto` with values in hierarchy.

**Comment by nvkelso** [comment]
Should the `parent_id` be Columbia (`85632519`) as that country administers this disputed area on the ground (it's already in the hierarchy, but parent_id is currently set to North America)?

(I suspect https://whosonfirst.mapzen.com/spelunker/id/85632563/#12/15.8243/-79.8653 should also have Columbia as the `parent_id`.)

**Comment by nvkelso** [comment]
Yes, `parent_id` should be Columbia (**85632519**). Make that fix, get the PR in a good place, and then assign to Aaron.

**Comment by stepps00** [comment]
The [last commit](https://github.com/whosonfirst-data/whosonfirst-data/pull/321/commits/f9be9819462cfc650329717e694318eb4e8e8fba):

* Updated the `parent_id` for Serranilla Bank record
* Exportified record, fixed broken PR

Over to @thisisaaronland for merge.

**Pull request merged**
