### PR TITLE
Updates to dependency records

### PR DESCRIPTION
**Pull request by stepps00**
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/954.

This PR only updated the `wof:lastmodified` date (and sometimes the machine-generated `geom:*` properties) by running them through the export tool.

Running this PR through the PIP tools should, in theory, update the dependency records and their descendants' `wof:hierarchy`, `wof:belongsto`, and `wof:parent_id` properties, which were stripped/updated in [a prior commit](https://github.com/whosonfirst-data/whosonfirst-data/commit/dd0dc23e29b0dbfb8378a625ebc99deb19d78aa0).

https://github.com/whosonfirst-data/whosonfirst-data/pull/915 has since been merged, so this PR _should_ clean-up and restore dependency records.

### CODE REVIEW

**Comment by nvkelso** [comment]
Assigning both @thisisaaronland and @stepps00 to coordinate PIP logic and dry runs.

**Comment by stepps00** [comment]
The most recent commit in this branch, 2394397, includes the following updates:

- Ensures that each dependency hierarchy contains only:
  - `empire_id`
  - `dependency_id` (itself)
  - `continent_id` (the continent that the dependency falls in)

- Sets the `wof:parent_id` value to the `empire_id` for each dependency

- Adds a `wof:controlled` property that contains:
  - `wof:hierarchy`
  - `wof:parent_id`

**Comment by nvkelso** [comment]
2x LGTM

**Comment by nvkelso** [comment]
This would require PIPing because all of these features's descendants need a hierarchy update. When we PIP'd these last there weren't a lot of venues in these places so expect LOE to be low.

**Pull request merged**
