### PR TITLE
Backfill mps:* props for meso sourced records

### PR DESCRIPTION
**Pull request by stepps00**
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/613.

This PR moves any `meso:mps_x` value to the `mps:longitude` property and any `meso:mps_y` value to the `mps:latitude` property.

At the time of import, some of the mesoshapes-sourced records' `mps:*` values were not updated, but the geometries were. This PR retains the `meso:mps*` properties and ensures that the current geometry's mapshaper value is stored in the `mps:*` property.

### CODE REVIEW

**Comment by nvkelso** [comment]
@stepps00 Please provide a few WOF:ids for me to verify.

**Comment by stepps00** [comment]
Re https://github.com/whosonfirst-data/whosonfirst-data/pull/939#issuecomment-337067360:

`data/421/170/577/421170577.geojson`
`data/421/170/585/421170585.geojson`
`data/110/878/564/3/1108785643.geojson`
`data/110/878/563/5/1108785635.geojson`
`data/110/878/563/7/1108785637.geojson`
`data/110/878/563/9/1108785639.geojson`

**Comment by nvkelso** [comment]
Noting here that the intention was to **copy** the values over rather than move them, and I've confirmed that's what happened in the example records.

**Comment by stepps00** [comment]
https://whosonfirst.mapzen.com/boundaryissues/pipeline/484/

**Pull request merged**
