### PR TITLE
New and updated France localadmin

### LINKED ISSUE #1094: Wrong geometries in France
Hi,
The geometries of quattroshapes are inaccurate in some places.
For example here we have [Villetaneuse](https://spelunker.whosonfirst.org/id/101751173) (in red) and [Montmagny](https://spelunker.whosonfirst.org/id/101750079/) (in blue) with borders coming from OpenStreetMap (black lines).

montmagny-villetaneuse

We can see very well that there is a part of Montmagny which is on the territory of Villetaneuse.
Because of this, some homes are misclassified with Pelias when using pip-whosonfirst during imports.
Would it be possible to retrieve geometries from OSM to update Who's On First?
Or are they too accurate and will be too heavy for Who's On First?

### PR DESCRIPTION
**Pull request by stepps00**
Replaces #1200, fixes #1094.

This PR includes all work needed to bring in new and updated `localadmin` records in France. Each record and descendants have been processed to update hierarchies.

After PIP work completed, I noticed various duplicate hierarchies. This was caused by ~1500 existing records not being marked as "non-current". This was fixed in https://github.com/whosonfirst-data/whosonfirst-data/commit/064289c9016edd598641d6e37acfaf48ec2bc5dc

Full, contiguous, non-overlapping localadmin coverage in France, as displayed in QGIS:
screen shot 2018-07-13 at 11 08 05 am

### CODE REVIEW

**Comment by nvkelso** [comment]
@stepps00 Can you prep files so we can look at this together, please?

**Comment by stepps00** [comment]
ids: [FR_localadmin_ids.txt](https://github.com/whosonfirst-data/whosonfirst-data/files/2237502/FR_localadmin_ids.txt)

**Comment by stepps00** [comment]
These features have funky hierarchies post-PIP, so I'm going to re-PIP features in this branch and check again...

- https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/stepps00/france-localadmin/data/114/190/657/3/1141906573.geojson
- https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/stepps00/france-localadmin/data/112/586/620/1/1125866201.geojson

Coverage looks correct, though:
screen shot 2018-07-31 at 3 45 53 pm

**Comment by stepps00** [comment]
Noting that re-PIPing these features does not change hierarchies.. notes about the two features above:

https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/stepps00/france-localadmin/data/114/190/657/3/1141906573.geojson
 - This is a record in French Guyana and has a record that includes both France and French Guyana (inheriting its parent's dual hierarchy). Hierarchy work was taken care of as part of #2.

https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/stepps00/france-localadmin/data/112/586/620/1/1125866201.geojson
  - This feature is actually correct. The parent records are current and have the correctly updated geometries.

**Comment by stepps00** [comment]
Fixed merge conflicts, shipping 🚢

**Pull request merged**
