### PR TITLE
Remapped bad name:* property values

### PR DESCRIPTION
**Pull request by stepps00**
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/817.

Updated records to remove bad `name:*` properties listed in issue.

If the record already had the correct `name:*` property that the bad `name:*` property should have been, the name value was appended to the existing property and the bad `name:*` proeprty was removed.

If a valid `name:` property did not exist, the `name:*` property was renamed.

Additionally, the last commit removes any duplicate name values in any updated property (not a common occurrence, but it did affect a few dozen records).

This PR can be committed without any PIP work.

### CODE REVIEW

**Comment by nvkelso** [comment]
LGTM so far :)

**Comment by stepps00** [comment]
Most recent commit takes care of any duplicate values that snuck into a single `name:*` property. 

Examples:

`data/858/630/05/85863005.geojson`
`data/858/630/01/85863001.geojson`
`data/890/537/237/890537237.geojson`

Note:
```
if props.has_key(v):
  name_prop = props[v]
  props[v] = list(set(name_prop))
```

**Comment by nvkelso** [comment]
@stepps00 I'm still seeing a few strange values like:

- `name:eng.p_x_preferred`
  - https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/stepps00/name-prop-updates/data/858/630/05/85863005.geojson
  - https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/stepps00/name-prop-updates/data/858/630/01/85863001.geojson

**Comment by stepps00** [comment]
@nvkelso - good catch.. somehow `name:eng.p_x_preferred` was not added to my lookup list and was not updated in records. I'll take a second look at any `name:*` property that includes `.p` and update in a new commit.

**Comment by stepps00** [comment]
@nvkelso - it looks like some of the bad `name:*` props with `.p` snuck through, but the last three commits should have taken care of _all_ bad `name:*` props across all records (examples linked above should be fixed).

PR is ready for another review.

**Comment by nvkelso** [comment]
Over to @thisisaaronland, property edits only for names, no PIP required.

**Pull request merged**
