### PR TITLE
New localadmin features for Austria

### PR DESCRIPTION
**Pull request by stepps00**
This PR fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/546.

Using locality data from the Austrian Open Data Portal ([source](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/austriaod.json)), new `localadmin` features were created for Austria. The [mesoshapes import script](https://github.com/mapzen/whosonfirst-toolbox/blob/master/scripts/import_mesoshape_files.py) was slightly modified to handle `localadmin` features and import the 2k new records for Austria.

### CODE REVIEW

**Comment by stepps00** [comment]
To do:

- Import all source-specific properties
- Add the `continent_id` for Europe in the `wof:hierarchy` and a pointer in the `wof:belongsto` property.

**Comment by stepps00** [comment]
Per discussion, no work around the `continent_id`, as this will be added during the PIP process.

**Comment by nvkelso** [comment]
Related PRs should all be PIP'd together:

- #700 WIP: New and updated county features for Austria
- #697 Updated geometries for Austrian region records, new alt-geoms

**Comment by nvkelso** [comment]
Over to @thisisaaronland. These are new features, and will need to be fully PIP'd to receive hierarchy, and for venues to incorporate this new placetype into their own hierarchies.

**Pull request merged**
