### PR TITLE
Updated Kazakhstan region records

### LINKED ISSUE #17: 85681273 is not a valid region of Kazakhstan
This polygon should surely belong to one of the other regions of the country. 

In FIPS format, +99 means other small island WTF knows what to do with, and that's where this funky data came from.

### PR DESCRIPTION
**Pull request by stepps00**
Fixes #17.

Updated three records in Kazakhstan. Split geometries of the Outyling Island record to the two correct `region` records.
- Deprecated and superseded record `85681273` (Outlying Island) to `85672889` and `85672923`. 
- Added island records of `85681273` to `85672889` and `85672923`, updating the `geometry` for both region records.
- Exportified

### CODE REVIEW

**Comment by nvkelso** [comment]
LGTM

**Comment by nvkelso** [comment]
Which issue is this attached to?

**Comment by thisisaaronland** [comment]
Holding back for testing with supersedes code since the descendants of these records should have their hierarchies updated accordingly.

**Comment by nvkelso** [comment]
@stepps00 Please fix the bad merge in this PR.

**Comment by stepps00** [comment]
Fixed the bad merge in this PR. Over to @thisisaaronland for import.

**Comment by stepps00** [comment]
Closing this outdated PR in favor of [this commit](https://github.com/whosonfirst-data/whosonfirst-data/commit/43ceb592557d58508000e8e58047241255838bb9).

**Pull request closed without merging**
