### PR TITLE
New admin0 alt_geom records for mesoshapes countries

### PR DESCRIPTION
**Pull request by stepps00**
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/611.

This PR includes new alt_geometry features for the countries that received mesoshapes updates. The admin2 features were dissolved and all sliver polygons/erroneous nodes were removed, then the [create_alt_geoms.py](https://github.com/mapzen/whosonfirst-toolbox/compare/stepps00/create-alt-geoms) script was used to do the following:

- Import the new dissolved geometry as an alt feature, with "meso" as a source
- Appended "meso" in the `src:alt_geom` list for each default record

This PR can be imported without any PIP work; no default record geometries were edited.

### CODE REVIEW

**Comment by stepps00** [comment]
To do: 

- [ ] Dissolve all features in Chile, import as a new alt_geometry record.
- [ ] Add pointer in Chile's default record to the new alt source (meso).
- [ ] Verify that all countries with `admin1` and `admin2` meso features were given a new dissolved alt_geometry record.

**Comment by nvkelso** [comment]
I've spot checked the records and their new alts and they look good :)

**Comment by stepps00** [comment]
Most recent commit(s) take care of Chile and updates to other alt_geoms; checklist above is done. This PR now has alt_geom records for all meso countries.

Over to @nvkelso for review/merge.

**Comment by nvkelso** [comment]
Over @thisisaaronland. This one is merge-able as is? We only added alt-geoms and pointers to the same in the primary feature records.

**Pull request merged**
