### PR TITLE
Mesoshapes - Admin1 updates, round 1

### PR DESCRIPTION
**Pull request by stepps00**
This PR includes updated `admin1` features for ~100 countries. Several commits have comments specific to that country or workflow. This PR includes the following:

- New and updated region and macroregion records 
- Updated `hasc:id` concordance for all features (for future Statoids join)

This PR does not include updated metafiles. Placing "(WIP)" in the title because there is likely additional work to do after review. 

This PR should fix the following issues: #628, #497, #486.

### CODE REVIEW

**Comment by stepps00** [comment]
**Note**: this branch contained 24 records with merge conflicts. This occurred in Libya, where work was completed on `admin1` records. The edits in master (those made in #555) were preferred because they contained alt-geometry information and an earlier `edtf:deprecated` date for a few records.

**Comment by thisisaaronland** [comment]
Two steps forward, one step back...

```
INFO:root:0 results page 1/1
INFO:root:find intersecting descendants of placetype intersection (for 85681255 (Minor islands of Iran))
INFO:root:count intersects: 0 (1 pages (1))
INFO:root:0 results page 1/1
Traceback (most recent call last):
  File "./pr-tool.py", line 424, in <module>
    pg_client.index_feature(feature, data_root=options.data_root, debug=options.debug)
  File "/usr/local/lib/python2.7/dist-packages/mapzen/whosonfirst/spatial/postgres.py", line 175, in index_feature
    repo = props["wof:repo"]
KeyError: 'wof:repo'
```

Pulling from master, then ensuring everything has a `wof:repo` property, then restarting...

**Comment by thisisaaronland** [comment]
Restarted Fri Jul  7 14:11:43 UTC 2017

**Comment by nvkelso** [comment]
@stepps00 I think you gave the 👍 to this yesterday? Who's responsible for fixing the conflicting file?

**Comment by thisisaaronland** [comment]
@stepps00 is

**Comment by thisisaaronland** [comment]
I also asked @stepps00 to "measure twice and cut once" because 85,000 files...

**Comment by stepps00** [comment]
The most recent commit fixed the merge conflict...

I'm going to spot check files again, then this should be ready for merge.

**Comment by nvkelso** [comment]
@stepps00 something else merged which resulted in more merge conflicts to fix...

**Comment by thisisaaronland** [comment]
I'm not convinced that there are merge conflicts anymore. I think it's just Git(Hub) being weird in the midst of a whole lot of change.

**Comment by stepps00** [comment]
The branch for this PR has been merged, the conflicts above seem to be phantom conflicts.. (?)

Closing this PR shortly.

**Pull request closed without merging**
