### PR TITLE
[wip] Great Britain: Add wof:coterminous fields to buffered point features

### PR DESCRIPTION
**Pull request by stepps00**
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/430.

This PR adds `wof:coterminous` fields to buffered point locality features (and their parent records) with an `iso:country` equal to `GB`.
- A list of locality records with a `"qs:type":"buffered point"` were gathered by running:

```
find /usr/local/mapzen/whosonfirst-data/data -type f -exec grep -l 
'"qs:type":"buffered point",' {} + | xargs grep  '"iso:country":"GB",' > grep.csv
```
- Using this list, a feature collection was created that contained all buffered point features in GB and their parent records. This feature collection projected in QGIS:

screen shot 2016-10-20 at 1 56 39 pm
- If the buffered point locality was parented by something than a localadmin, it was not given a `wof:coterminous` property. If the buffered point locality was parented by a large localadmin record (highlighted in the above image) that had a geometry too large to be coterminous with the locality, it was also not given a `wof:coterminous` property.
- A version of [this script](https://github.com/mapzen/whosonfirst-toolbox/blob/master/scripts/add-field.py) was used to give new `wof:coterminous` properties to the remaining buffered point records and their parent records.

### CODE REVIEW

**Comment by stepps00** [comment]
This could be done on a larger scale, possibly for all features with a `"qs:type":"buffered point"`, but logic would be needed to ensure a `wof:coterminous` link wasn't given to a locality record and say, a large region or county record.

**Comment by nvkelso** [comment]
Add specific script variant to Toolbox with new name (in the comments at the top of that script, say it's based on something else...)

**Comment by nvkelso** [comment]
This is a good first cut, but let's be more conservative and _only_ automatically set the `localadmin` and `locality` as coterminous when the names are an exact match.

For instance, [Nettlestone ](https://whosonfirst.mapzen.com/spelunker/id/101852305/) and [Nettlestone And Seaview](https://whosonfirst.mapzen.com/spelunker/id/404445543/) seem like they should **not** be coterminous. The names are slightly different, and imply there are two localities here. 

Note also the poor capitalization in the previous name (`And`), so maybe say exact match on lowercase name (not original string).

**Comment by nvkelso** [comment]
Please also make sure you manually review that the `Newbury` of the primary issue is still resolved after this!

**Comment by nvkelso** [comment]
Related to https://github.com/whosonfirst-data/whosonfirst-data/issues/538.

**Comment by nvkelso** [comment]
Let's defer this one a while yet.

**Comment by stepps00** [comment]
Commit 7cfff413d5d1c2501a2131f4489ac2a9a939fa70 fixes merge conflicts.
Commit e8e63124262a8839d64caa432c39e9ab26527201 converts `wof:coterminous` properties to lists.

**Comment by stepps00** [comment]
Closing this in preference of a new, clean PR. This work is tightly knit with #53.

**Pull request closed without merging**
