### PR TITLE
Fix St Petersburg, Russia

### PR DESCRIPTION
**Pull request by stepps00**
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/948.

- Commit 4ac7f8c tagged the region record of St Petersburg as coterminous with a new locality record of St Petersburg.
- Commit ca350bc deprecated all existing descendant locality records of the St Petersburg region.
- Commit 7605c7bccd50e560492f750dba417ac290c9af92 created seven new localadmin records (WOF currently has eleven of the eighteen localadmin records) and linked the supersedes/superseded_by properties of these new localadmin records with the appropriate deprecated locality.
- Commit 49f6338 adjusted the `wof:hierarchy` to include all eighteen localadmin parents.
- Commit 5b987e6 added a `wof:controlled` property and updated the `wof:parent_id` property of the St Petersburg locality.
- Commit 0d14e1d superseded the Leningrad records into St Petersburg
- Commit 67a98cf swapped the placetypes of the new `localadmin` to `borough`
- Commit 64e38f0 supersedes all `county` records into new `localadmin` records
- Commit 8ff0ae8 supersedes existing `localadmin` records into new `borough` records
- Commit e14c1ab adds a remarks file, and updates the hierarchy to **only** include empire, continent, country, and locality.
- Commit ebf016b addresses https://github.com/whosonfirst-data/whosonfirst-data/pull/1024#issuecomment-342663682 by merging geometries for a single "Leningrad", superseding appropriate records, and adding `edtf:deperecated` dates to three of the "bad" Leningrad records. 
- Commit 08dc303a9d41f8bae94077d276406cd1a58d48c2 adds an `edtf:inception` date to the historical record of Leningrad.

### CODE REVIEW

**Comment by stepps00** [comment]
To do:

- [ ] Verify superseding
- [ ] Historical superseding of Leningrad/St Petersburg
- [ ] Review neighbourhoods and counties...

**Comment by Chypa74** [comment]
@stepps00 Could you tell me please, when this proposed addition will be approved?

**Comment by nvkelso** [comment]
We’re aiming for early this coming week.

**Comment by nvkelso** [comment]
> Commit 0d14e1d superseded the Leningrad records into St Petersburg

What's the right thing to do here? I'd expect 1 of the Leningrad records is legit, the others are not, and the legit one gets edtf dates for it's actual history as a place? @thisisaaronland what do you think?

**Comment by thisisaaronland** [comment]
We appear to have had (4) separate records for Leningrad:

* https://whosonfirst.mapzen.com/spelunker/id/102002167/
* https://whosonfirst.mapzen.com/spelunker/id/102002171/
* https://whosonfirst.mapzen.com/spelunker/id/102008119/
* https://whosonfirst.mapzen.com/spelunker/id/102008121/

At a glance I would say that it looks like the weird atomizing of localities in to multiple shapes that sometimes happened in QS ?

My comments would be:

(1) of these records is "correct", as in "Leningrad" actually existed in 1991 and the other (3) are bunk as in "they should never have been created". So:

* We should pick one of the four and make it "Leningrad c. 1991" and have it be superseded by "St. Petersburg c. 1991"
* The remaining (3) records for Leningrad should be marked as deprecated and probably superseded by the "good" record for Leningrad (c. 1991)
* We should update the geometry for the "good" record with something approximating (or matching) the shape of the city in 1991

**Comment by stepps00** [comment]
The most recent commit (ebf016b) addresses https://github.com/whosonfirst-data/whosonfirst-data/pull/1024#issuecomment-342663682 by merging geometries for a single "Leningrad", superseding appropriate records, and adding `edtf:deperecated` dates to three of the "bad" Leningrad records.

**Comment by stepps00** [comment]
This file should contain paths to all updated records in this PR: [updated_ids.txt](https://github.com/whosonfirst-data/whosonfirst-data/files/1455962/updated_ids.txt).

**Comment by Chypa74** [comment]
@nvkelso Could you tell me please, when this fix will be merged into master branch?

**Comment by nvkelso** [comment]
@Chypa74 after the merge conflicts are dealt with, sometime this week.

**Comment by stepps00** [comment]
The most recent commit fixes merge conflicts. This has been added to the priority list as the next "to do" PR.

**Pull request merged**
