### PR TITLE
Added wof:label field for all county records in US and PR

### PR DESCRIPTION
**Pull request by stepps00**
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/217.

* Added `wof:label` fields to all county records in the United States and Puerto Rico, per request by search team
* Added `name:spa_x_preferred` field to all county records in Puerto Rico
* If the county record already had a `name:spa_x_preferred` field, it was preserved and moved to a `name:spa_x_variant` field
* Exportified to updated last modified date

Script used for this work will be added to the toolbox repo.

### CODE REVIEW

**Comment by nvkelso** [comment]
Overall good.

But I'm seeing a few places where the Spanish preferred name is losing is accent mark when the " county" is added on.

Example:

* data/102/080/443/102080443.geojson

```
   ],
      "name:spa_x_preferred":[
 +        "Municipio Bayamon"
 +    ],
 +    "name:spa_x_variant":[
          "Bayam\u00f3n"
      ],
      "wof:id":102080443,
 +    "wof:label":"Municipio de Bayamon",
      "wof:name":"Bayam\u00f3n",
```

**Comment by nvkelso** [comment]
(We think this is an error in the python script used, be sure to update the toolbox not just the PR.)

**Comment by stepps00** [comment]
Issue was due to `utf-8` encoding, similar to what happened with the import-mesoshapes.py script. I'll update the toolbox script and file a PR.

As for the Puerto Rican county records in this PR - they should all be updated with correct `wof:label` and `name` fields. Your example above now reads as:

```
   ],
      "name:spa_x_preferred":[
 +        "Municipio Bayam\u00f3n"
 +    ],
 +    "name:spa_x_variant":[
          "Bayam\u00f3n"
      ],
      "wof:id":102080443,
 +    "wof:label":"Municipio de Bayam\u00f3n",
      "wof:name":"Bayam\u00f3n",
```

This PR should be ready to merge. No PIP work required.

**Comment by nvkelso** [comment]
LGTM

**Pull request merged**
