### PR TITLE
1.5k new locality features from Natural Earth

### PR DESCRIPTION
**Pull request by nvkelso**
Most of Natural Earth's ~7.3k features were found to already be included in WOF, but around 1,542 features were found to be missing. This PR takes @stepps00's additions in the general **min_zoom** properties PR https://github.com/whosonfirst-data/whosonfirst-data/pull/867 and moves them to this branch for PIPing.

screen shot 2017-07-31 at 16 50 41

### CODE REVIEW

**Comment by nvkelso** [comment]
@stepps00 Can you checkout that this set looks like the original set you added, please?

**Comment by nvkelso** [comment]
Over to @thisisaaronland.

Requires PIPing. 

- 1,542 features locality features total (global coverage)

**Comment by thisisaaronland** [comment]
This has started, in debug mode. Like 660 it involves basically the entire planet. We should stop making PRs like this because they will take forever to run and make it hard to track down problems if and when they arise.

**Comment by thisisaaronland** [comment]
Over to @stepps00 for sanity checking : https://github.com/whosonfirst-data/whosonfirst-data/compare/pr-876

**Comment by stepps00** [comment]
I reviewed https://github.com/whosonfirst-data/whosonfirst-data/compare/pr-876 and spot-checked the hierarchies of several records - the PR looks good to me.

**Pull request merged**
