### PR TITLE
Update 'name:eng_x_preferred'

### PR DESCRIPTION
**Pull request by missinglink**
Update 'name:eng_x_preferred' to reflect the common English name.

### CODE REVIEW

**Comment by nvkelso** [comment]
@missinglink Thanks, this is a good fix! Can you please also update the `wof:name` to **Rome**? And make this change also for the [locality](https://spelunker.whosonfirst.org/id/101752607/) and [localadmin](https://spelunker.whosonfirst.org/id/404461721/) records?

(Because Roma is already in other name properties – namely Italian – lifecycle rules around new IDs aren't triggered.)

**Comment by missinglink** [comment]
@nvkelso GTG

**Comment by nvkelso** [comment]
@stepps00 can you look at exportifying these and then we an merge, please? And then the merge conflict.

**Comment by stepps00** [comment]
Thanks @missinglink! I just merged #1557, which included work to Rome records. Closing.

**Pull request closed without merging**
