### PR TITLE
Fix typo Rgers -> Rogers

### PR DESCRIPTION
**Pull request by orangejulius**
Thanks to @stevevance for catching it

@thisisaaronland let me know if you'd like me to also update the zetashapes label (`zs:label`) which has the same typo

### CODE REVIEW

**Comment by stevevance** [comment]
How did you find where the typo was printed?

**Comment by orangejulius** [comment]
I knew it was in this file so I just used grep :P

**Comment by nvkelso** [comment]
We don't modify `zs` props, updating the `wof:name` and `name` props are fine. Thanks!

**Comment by stepps00** [comment]
[Last commit](https://github.com/whosonfirst-data/whosonfirst-data/pull/1083/commits/6502437506896619155a23f1db238d13a23d077b) exportified record for import.

**Pull request merged**
