### PR TITLE
WIP: GeoNames locality points import

### PR DESCRIPTION
**Pull request by stepps00**
WIP, 4/4.

Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/108.

### CODE REVIEW

**Comment by stepps00** [comment]
@nvkelso - this should be it for the GN locality import...

**Comment by nvkelso** [comment]
How many new records in this PR? And yes, let's wait for it to finish all the way before merging...

**Comment by stepps00** [comment]
This PR will include the last of the locality import.. it should wrap up shortly and will include the remaining ~1.5M

**Comment by nvkelso** [comment]
Waiting up to 24 hours for related/unrelated computer processes to finish.

**Pull request merged**
