### PR TITLE
UK: placetype cleanup

### PR DESCRIPTION
**Pull request by stepps00**
This PR will fix the first portion of UK edits outlined in #1367 (changes, minus `locality` placetype)

Changes include:

- [x] Add new ceremonial county records at the region placetype
- [x] Move existing region records to the county placetype
- [x] Set the localadmin and region records in Scotland as coterminous
- [x] Add names to records missing `wof:name` values
- [x] Adds new region records to Northern Ireland
- [x] Flag existing region records in Northern Ireland as not current, update props appropriately
- [x] Review all `mz:is_current` properties
- [x] Validate geometries (no changes needed, all geometries are valid)
- [x] Tag regions and counties as coterminous, when geometries are the same
- [x] Tag label hierarchy of 0 for regions in Scotland
- [x] Fix any NULL localadmin names
- [x] Verify N Ireland placetypes (and placetype alts)
- [x] Add `county` to placetype_alt of London or make new/coterminous record with label hierarchy 0.
- [x] Update `buffered point` geometries to points, with appropriate property flags
- [x] Flag null localadmin as statistical gore, no hier label, and update name
- [x] PIP

To do:
- [x] Review

### CODE REVIEW

**Comment by stepps00** [comment]
3c9d647 - new ceremonial county (region) records for GB

Adds new `region` records, which represent the 91 ceremonial counties in the UK.

45d5330 - simplify three large geoms, update src props

Modifies the geometries of three of the new regions, bringing the file sizes down from ~20mb in size, updates `src:` properties appropriately.

13f4672 - move existing regions to county placetype, supersede, new records

Moves the existing `region` records to the `county` placetype, superseding records and updating properties.

4709863 - City of London name swapping

Updates the `wof:name` and various `name:*` properties to the borough record for the City of London, specifically for #1364.

0915985 - set scotland localadmin/regions as coterminous, flag as current

Sets the `localadmin` and `region` records in Scotland as coterminous.

097c28c - add names to localadmin in scotland that have no name...

All but two of the `localadmin` records in Scotland were missing a `wof:name` value, this commit updates the names for these records and sets the `name:eng_x_preferred` property.

1a0c145 - cessation and is current = 0 for existing N Ireland regions

Region records in Northern Ireland were updated in 2015, bring the placetype count down from 26 to 11. This commit adds a cessation date of 2015 to the existing regions in Northern Ireland and sets the `mz:is_current` value to 0 for each record.

e290e6c - new regions for N Ireland

Adds new `region` records to Northern Ireland.

86e0827 - supersedes work for N Ireland regions

Updates the `wof:superseded_by` and `wof:supersedes` values for current and non-current `region` records in N Ireland.

528beef - add inception dates to N Ireland regions records

Adds a "2015" inception date to the 11 new regions.

**Comment by stepps00** [comment]
Tagging @nvkelso for review, PIP work to be done once things look good.

**Comment by nvkelso** [comment]
> 96a7922 - remove Filler Area localadmin

@stepps00 does the UK generate "census" stats for those filler areas? For example, do they have a unique code that can be joined to population other statistical information? If so perhaps they shouldn't be dropped entirely but marked as a `gore`?

**Comment by stepps00** [comment]
@nvkelso  re: https://github.com/whosonfirst-data/whosonfirst-data/pull/1368#issuecomment-437442477

The source file contains a unique code on each feature, but the code does not map to any statistic/lookup table. I compiled the Ordnance Survey names csv files into a single shapefile of points and compared the points to these Filler Areas to find a useable name, but that resulted in a many-to-one join for each feature (and still no usable names).

We could keep these records and mark them with the `wof:statistical_gore` property, but the features would still not have a name.

**Comment by nvkelso** [comment]
Please also consider London as a `county`, either as new coterminous feature with label hierarchy 0.

**Comment by nvkelso** [comment]
For all the "not current" localadmin in this PR, please instead set their name to `""` (empty string) and their label hierarchy to 0, and their statistical gore to 1, and reset them to is_current = 1.

And take any localtiy polygon that is qs_type of `Buffered Point` and store polygon as alt, and reset default geom to simple latlng point.

**Comment by missinglink** [comment]
Sorry to be nit-picky, can we please fix this https://github.com/whosonfirst-data/whosonfirst-data/issues/1364#issuecomment-437858619 before merging?

**Comment by stepps00** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/pull/1368#issuecomment-437859270

Yeah, that seems fine to me. I'll add a commit before merging that updates that name. Thanks for the clarification.

**Comment by nvkelso** [comment]
LGTM, go ahead and PIP :)

**Comment by stepps00** [comment]
3795ab4 includes all PIP work to update hierarchies and parent ids for all records in the UK. I'd like to do a bit more QA before merging this PR.

**Comment by stepps00** [comment]
The following records need reversegeo lat/long values (and re-PIPing) before merging:

```
1360699247
1360698897
404448343
1360698531
1360698747
404431949
101873739
101873741
101873743
101873747
101873749
101873751
101873753
101873755
101873757
101873775
101873777
101873791
101874215
101874217
```

Aside from this, the changes in this PR look good to me.

**Comment by stepps00** [comment]
PIP work is done in this PR for the above list of records. I'll review and merge shortly.

**Pull request merged**
