### PR TITLE
Updated Buenos Aires neighbourhoods

### PR DESCRIPTION
**Pull request by stepps00**
WIP. This PR is a local copy of (and replaces) #816.

To do:

- [x] Exportify all records
- [x] Verify superseding values
- [x] Verify `mz:* properties
- [x] Collect all modified records and validate placetypes in QGIS

### CODE REVIEW

**Comment by stepps00** [comment]
Records and properties look ready to merge, adding this PR to the priority list (https://github.com/whosonfirst-data/whosonfirst-data/issues/864).

This will need to PIP'd to ensure that any potential descendants are updated with new hierarchies.

**Comment by thisisaaronland** [comment]
@mfogel - can you explain what's going with stuff like this:

https://github.com/whosonfirst-data/whosonfirst-data/pull/881/commits/9aa626d760d73209efd7b3f6e78d9f90725ec230#diff-3b43fdb5e9a220e241ee13c9c1de0caa

Because it is triggering errors like this when we try to process the PR:

ERROR:root:/usr/local/data/whosonfirst-data/data/111/871/781/5/1118717815.geojson does not exist locally, did you merge the PR?

Looking at the commit history it appears that a bunch of files were renamed? How do I know which files should be expected to be present (based on the commit history) versus those that are okay to skip?

**Comment by mfogel** [comment]
@thisisaaronland - What happening here is that there are 15 records that underwent 'significant events' in this PR, so they got new ID's. I originally didn't realize the Brooklyn minted ID's where anything more than chosen random without collisions, so I randomly selected 15 new ID's for the new records. One of the other mapzen folks queued me into the fact that you do need to use the brooklyn ints (monotonic increasing), so I changed those 15 new records to use newly-minted brooklyn ints. That commit you reference above is that change - fixing the bad ids to be good ones. Here's my original confusion: https://github.com/whosonfirst-data/whosonfirst-data/pull/816#issuecomment-306668128

The records with the bad ID's were added in https://github.com/whosonfirst-data/whosonfirst-data/pull/881/commits/12127a7ccf874e23a5145f8672275be1d9d51762, and then fixed in the commit you reference, https://github.com/whosonfirst-data/whosonfirst-data/commit/9aa626d760d73209efd7b3f6e78d9f90725ec230

As far as fixing the problem - I can provide a new, identical PR without those bad ids in the history by tomorrow morning it that works for you all. Should be pretty easy to diff it with this one to ensure it's identical. Let me know if this works for you.

If you're in a rush and need to do this today - perhaps squash all of my commits? Or perhaps squash from (and including) https://github.com/whosonfirst-data/whosonfirst-data/pull/881/commits/12127a7ccf874e23a5145f8672275be1d9d51762 to https://github.com/whosonfirst-data/whosonfirst-data/commit/9aa626d760d73209efd7b3f6e78d9f90725ec230 Or do this in two merges: one up to and including https://github.com/whosonfirst-data/whosonfirst-data/pull/881/commits/12127a7ccf874e23a5145f8672275be1d9d5176, and then another that includes the remainder of the commits on this PR.

**Comment by thisisaaronland** [comment]
I need to get some food before I look over your comments carefully, but briefly: Brooklyn Integers are not "random". I mean... we're talking about "artisanal" integers so it's all a bit "fluid" but the short version is:

http://brooklynintegers.com/create

The longer version is:

http://brooklynintegers.com/about/

The long version is:

http://www.neverendingbooks.org/artisanal-integers

The more-than-you-could-ever-imagine-someone-thinking-about-this is:

http://www.aaronland.info/weblog/2012/12/01/coffee-and-wifi/#timepixels

**Comment by thisisaaronland** [comment]
@mfogel if you have the list of 15 bunk IDs handy it might be easier and faster (for everyone) for me to just special case them.

**Comment by mfogel** [comment]
Sure thing. The bunk IDs are:

1118717815
1118717817
1118717819
1118717823
1118717825
1118717827
1118717829
1118717831
1118717833
1118717835
1118717837
1118717841
1118717843
1118717845
1118717847

**Comment by thisisaaronland** [comment]
Great, thanks. I will circle back to this once some other update work is
done.

**Comment by mfogel** [comment]
@thisisaaronland I took a look over https://github.com/whosonfirst-data/whosonfirst-data/commit/675fc69c72f3dcc78225492a65b42569c603cf00 and two thoughts:

 * this caught some embarrassing mistakes on my part. Mainly that I didn't switch out the bunk Id's for good ones in the neighborhood records. So much for editing 100 json files by hand... I'm glad this was caught before merging this in. Sorry about that!
 * To make sure the hierarchy is now correct, I manually walked through all 48 official neighborhoods and verified they all now point to the correct borough record. Looks good.

I did run across a small error that could be fixed before merging - concerning the name of one of the neighborhoods. The name of the neighborhood is actually ['Versalles', not 'Versailles'](http://www.buenosaires.gob.ar/laciudad/barrios/versalles). Minor - but if you want it, [this is a one-line commit](https://github.com/mfogel/whosonfirst-data/commit/cc2e6f29e3ac94afb45ee00590748f673275333e) that should apply cleanly to the `pr-881` branch that fixes the name.

**Comment by nvkelso** [comment]
@mfogel The Buenos Aires neighbourhoods have been merged to master. Thanks so much for your help with this! Will you be using them in a project?

**Comment by mfogel** [comment]
Great! Thanks for accepting the contribution. Appreciate very much you all taking the time to work with me to get it into master. How often do you push out a new build to production - ie when will I see the new records in spelunker and https://whosonfirst.mapzen.com/data/ ? 

I will be using the records in a project. I'm building an app/site that allows a user to track their travels via a series of travel maps. So, track your progress on 'Travel to all 50 states' or 'All countries of the world' or... 'all neighborhoods of Buenos Aires'. Having just moved from SF to BA earlier this year that last one is high on my list :)

**Comment by nvkelso** [comment]
We usually push to prod right after the merge. But I don't see the new data in prod yet, for instance `85767083` was deprecated in the PR but that [isn't reflected](https://whosonfirst.mapzen.com/spelunker/id/85767083/) in the Spelunker. @thisisaaronland can you take a look, please?

Your app sounds fun, please keep us updated!

**Comment by thisisaaronland** [comment]
Unsure why this happened but I've manually ensured that the data (on the big honking data) is in sync with `master` and kicked off jobs to update all the databases. If stuff is still not there (the Spelunker, etc.) in the morning then... well, that will be weird.

**Comment by nvkelso** [comment]
Missing data sounds similar to https://github.com/whosonfirst/whosonfirst-www-spelunker/issues/129?

**Comment by nvkelso** [comment]
I see the PR data in the Spelunker now. @mfogel please confirm the rest.

**Comment by mfogel** [comment]
@nvkelso Looks good, I see updated geometry for all the records addressed in this PR now.

Probably safe to close #180 now.

**Pull request merged**
