### PR TITLE
[do not merge] Philippines: fix hierarchy and labels in National Capital Region

### PR DESCRIPTION
**Pull request by noizde**
This addresses the problems described in #1214, with the National Capital Region and its cities being encoded as a counties, regions, and localities, with resulting in some bizarre hierarchies:

image

The hierarchical errors can be verified by checking the areas' respective [Philippine Standard Geographic Code](http://nap.psa.gov.ph/activestats/psgc) entries.

To begin, I selected these records to be edited:
- National Capital Region, a.k.a. Metro Manila: [1108697351](https://data.whosonfirst.org/110/869/735/1/1108697351.geojson)
- Cities
   - Caloocan: [85676383](https://data.whosonfirst.org/856/763/83/85676383.geojson), superseding [421191573](https://data.whosonfirst.org/421/191/573/421191573.geojson)
   - City of Manila: [85676375](https://data.whosonfirst.org/856/763/75/85676375.geojson), superseding [421168919](https://data.whosonfirst.org/421/168/919/421168919.geojson)
   - Las Piñas: [85676423](https://data.whosonfirst.org/856/764/23/85676423.geojson), superseding [1125396479](https://data.whosonfirst.org/112/539/647/9/1125396479.geojson)
   - Makati: [85676413](https://data.whosonfirst.org/856/764/13/85676413.geojson), superseding [421168541](https://data.whosonfirst.org/421/168/541/421168541.geojson)
   - Malabon: [85676385](https://data.whosonfirst.org/856/763/85/85676385.geojson), superseding [890443015](https://data.whosonfirst.org/890/443/015/890443015.geojson)
   - Mandaluyong: [85676369](https://data.whosonfirst.org/856/763/69/85676369.geojson), superseding [421191575](https://data.whosonfirst.org/421/191/575/421191575.geojson)
   - Marikina: [85676399](https://data.whosonfirst.org/856/763/99/85676399.geojson), superseding [421200223](https://data.whosonfirst.org/421/200/223/421200223.geojson)
   - Muntinlupa: [85676429](https://data.whosonfirst.org/856/764/29/85676429.geojson), superseding [421169757](https://data.whosonfirst.org/421/169/757/421169757.geojson)
   - Navotas: [85676379](https://data.whosonfirst.org/856/763/79/85676379.geojson), superseding [421198571](https://data.whosonfirst.org/421/198/571/421198571.geojson)
   - Parañaque: [85676419](https://data.whosonfirst.org/856/764/19/85676419.geojson), superseding [421189355](https://data.whosonfirst.org/421/189/355/421189355.geojson)
   - Pasay: [85676415](https://data.whosonfirst.org/856/764/15/85676415.geojson), superseding [421169759](https://data.whosonfirst.org/421/169/759/421169759.geojson)
   - Pasig: [85676407](https://data.whosonfirst.org/856/764/07/85676407.geojson), superseding [421169761](https://data.whosonfirst.org/421/169/761/421169761.geojson)
   - Pateros: [85676437](https://data.whosonfirst.org/856/764/37/85676437.geojson), superseding [421187125](https://data.whosonfirst.org/421/187/125/421187125.geojson)
   - Quezon City: [85676395](https://data.whosonfirst.org/856/763/95/85676395.geojson), superseding [421195243](https://data.whosonfirst.org/421/195/243/421195243.geojson)
   - San Juan: [85676403](https://data.whosonfirst.org/856/764/03/85676403.geojson), superseding [421191577](https://data.whosonfirst.org/421/191/577/421191577.geojson)
   - Taguig: [85676433](https://data.whosonfirst.org/856/764/33/85676433.geojson), superseding [421191579](https://data.whosonfirst.org/421/191/579/421191579.geojson)
   - Valenzuela: [85676389](https://data.whosonfirst.org/856/763/89/85676389.geojson), superseding [890437255](https://data.whosonfirst.org/890/437/255/890437255.geojson)

I used a script to set [1108697351](https://spelunker.whosonfirst.org/id/1108697351/) as a `region` placetype (rather than `county`) belonging to the Philippines, and updating the hierarchy to reflect that.

Next, this script processed each city. Most of them are named `National Capital Region`, so for these cities (more appropriately, localities), so this script sets their `name:eng_x_preferred` to the value of `wof:name`, if no other sources are present (discussed later). It then sets the `wof:belongsto`, `wof:parent_id`, and `wof:hierarchy` properties, reflecting that they should be child localities of the above National Capital Region record. Their `wof:placetypes` are changed to `locality`, from `region`.

Many of the records to be superseded have more accurate `name:*` values, so the script copies those over to the superseding record. The superseded records also have data for `qs:*`, `ne:*`, and `wof:concordances`, which are also copied over to the superseding record.

It then adds the appropriate `wof:supersedes` and `wof:superseded_by` values, and adds the old geometries as `geom_alt`s, appending the appropriate `src:geom` to the superseding record's `src:geom_alt` and creating new alternative geometry files. In this instance, all of the new alternative geometries are taken from `quattroshapes_pg`. This also updates the superseded records' `mz:is_current` values to `0`.

This generates the following new alternative geometry records:
```
85676385-alt-quattroshapes_pg.geojson
85676375-alt-quattroshapes_pg.geojson
85676419-alt-quattroshapes_pg.geojson
85676423-alt-quattroshapes_pg.geojson
85676389-alt-quattroshapes_pg.geojson
85676369-alt-quattroshapes_pg.geojson
85676395-alt-quattroshapes_pg.geojson
85676429-alt-quattroshapes_pg.geojson
85676399-alt-quattroshapes_pg.geojson
85676433-alt-quattroshapes_pg.geojson
85676403-alt-quattroshapes_pg.geojson
85676415-alt-quattroshapes_pg.geojson
85676437-alt-quattroshapes_pg.geojson
85676407-alt-quattroshapes_pg.geojson
85676379-alt-quattroshapes_pg.geojson
85676413-alt-quattroshapes_pg.geojson
85676383-alt-quattroshapes_pg.geojson
```

This changeset is simply a reorganization data of already in WoF, and does not ingest any new sources.

Some context on the scope and usage: we're working on local transit directions around Metro Manila at [Sakay.ph](https://sakay.ph/), and WoF looks quite promising in conjunction with [Pelias](https://github.com/pelias) for our geocoding needs! We're looking forward to setting that up and seeing where that takes us.

### CODE REVIEW

**Comment by nvkelso** [comment]
Summarizing from https://github.com/whosonfirst-data/whosonfirst-data/issues/1214#issuecomment-398565648...

Please also set a `wof:placetype_alt` on **National Capital Region** to `macroregion`

We need to add / link to an issue to track adding all the other `macroregion`s in the Philippines.

**Comment by nvkelso** [comment]
We also need to use the WOF exportify tool to property format the GeoJSON records – otherwise the git diffs are super confusing.

**Comment by nvkelso** [comment]
Let's also ensure that all the 17 localities in Manila area are `locality` placetype (so regions should superceed into locality features, and if the region geometry was better that should copy over, same for properties).

**Comment by nvkelso** [comment]
@noizde Thanks so much for this PR, it's a huge step toward fixing up records in Manila which were quite scrambled. 

@stepps00 Can you help rework this PR to address the above PR comments and issue comments, please?

**Comment by stepps00** [comment]
@noizde - echoing what @nvkelso said above, thank you for this PR. I will be addressing a few issues in new commits in the coming days and anticipate merging soon. Stay tuned.

**Comment by nvkelso** [comment]
> Could I ask what the common usage of macroregion is versus region? Or, in this case, how they would correspond to the local units?

From ISO we see 17 "regions" which I propose mapping to WOF `macroregion` since WOF already maps the ISO provinces to `region` (this is WOF's convention generally from ISO):

Code | Subdivision name (en) | Subdivision name (tl)
---- | ------ | --------
PH-14 | Autonomous Region in Muslim Mindanao (ARMM) | Nagsasariling Rehiyon ng Muslim sa Mindanaw[1]
PH-05 | Bicol (Region V) | Rehiyon ng Bikol
PH-02 | Cagayan Valley (Region II) | Rehiyon ng Lambak ng Kagayan
PH-40 | Calabarzon (Region IV-A) | Rehiyon ng Calabarzon
PH-13 | Caraga (Region XIII) | Rehiyon ng Karaga
PH-03 | Central Luzon (Region III) | Rehiyon ng Gitnang Luson
PH-07 | Central Visayas (Region VII) | Rehiyon ng Gitnang Bisaya
PH-15 | Cordillera Administrative Region (CAR) | Rehiyon ng Administratibo ng Kordilyera
PH-11 | Davao (Region XI) | Rehiyon ng Dabaw
PH-08 | Eastern Visayas (Region VIII) | Rehiyon ng Silangang Bisaya
PH-01 | Ilocos (Region I) | Rehiyon ng Iloko
PH-41 | Mimaropa (Region IV-B) | Rehiyon ng Mimaropa
PH-00 | National Capital Region | Pambansang Punong Rehiyon
PH-10 | Northern Mindanao (Region X) | Rehiyon ng Hilagang Mindanaw
PH-12 | Soccsksargen (Region XII) | Rehiyon ng Soccsksargen
PH-06 | Western Visayas (Region VI) | Rehiyon ng Kanlurang Bisaya
PH-09 | Zamboanga Peninsula (Region IX) | Rehiyon ng Tangway ng Sambuwangga

> There are also some cases where there are multiple places with the same name - there's a Las Piñas (a barangay, which is the smallest government unit) within the municipality of Peñaranda in the province of Nueva Ecija in Region III, for example, with data mixed in with the Las Piñas city/locality within the National Capital Region. Should this be a raised as a separate issue?

Please give some examples? Yes, a new issue is probably best.

**Comment by noizde** [comment]
Got it, thanks. I've submitted #1232 which I think covers all of the mis-assigned data on the locality level.

**Comment by stepps00** [comment]
Hey @noizde - at the moment, I am processing the PR for #1200. Once this is complete, I will hop onto this PR and process. 

I've been merging various PRs recently, hence the merge conflicts in this PR. Once I've cleared the merge conflicts here, I will ping you with any questions that come up...

**Comment by stepps00** [comment]
@noizde - realizing here that the changes here are coming from your external `by-implication:ph-ncr-cleanup` branch. Are you able to pull from the `master` branch and resolve conflicts? If so, I can review and suggest any new changes.

Also, each record that is imported and changed in Who's On First needs to be run through out [export tools](https://github.com/whosonfirst/py-mapzen-whosonfirst-export) (specifically, the [exportify](https://github.com/whosonfirst/py-mapzen-whosonfirst-export/blob/master/scripts/wof-exportify) tool) to ensure that they have necessary properties and are formatted appropriately. Each of the 52 files in this PR will need to be run through these export tools before import. Would you like to give this a shot? Otherwise, I can copy your changes into a local branch to review and export. 

Let me know what is easiest for you.

**Comment by noizde** [comment]
@stepps00 Thanks for the quick response! I'll try to resolve the conflicts and use the exportify tool on my end, and let you know.

**Comment by noizde** [comment]
@stepps00 I've fixed the conflicts - they were mostly records for which languages were added resulting in `lastmodified` being incremented, apart from the record referring to the City of Manila, which had some conflicting concordances that referred to Metropolitan Manila (aka NCR).

I'm having trouble fetching the dependencies for the exportify tool - I'm wondering if this has something to do with the `--process-dependency-links` caveat noted on the Readme. If this is something you've already got set up, could you be the one to handle export?

The list of changed files is as follows:
```
data/110/869/735/1/1108697351.geojson
data/112/539/647/9/1125396479.geojson
data/421/168/541/421168541.geojson
data/421/168/919/421168919.geojson
data/421/169/757/421169757.geojson
data/421/169/759/421169759.geojson
data/421/169/761/421169761.geojson
data/421/187/125/421187125.geojson
data/421/189/355/421189355.geojson
data/421/191/573/421191573.geojson
data/421/191/575/421191575.geojson
data/421/191/577/421191577.geojson
data/421/191/579/421191579.geojson
data/421/195/243/421195243.geojson
data/421/198/571/421198571.geojson
data/421/200/223/421200223.geojson
data/856/763/69/85676369-alt-quattroshapes_pg.geojson
data/856/763/69/85676369.geojson
data/856/763/75/85676375-alt-quattroshapes_pg.geojson
data/856/763/75/85676375.geojson
data/856/763/79/85676379-alt-quattroshapes_pg.geojson
data/856/763/79/85676379.geojson
data/856/763/83/85676383-alt-quattroshapes_pg.geojson
data/856/763/83/85676383.geojson
data/856/763/85/85676385-alt-quattroshapes_pg.geojson
data/856/763/85/85676385.geojson
data/856/763/89/85676389-alt-quattroshapes_pg.geojson
data/856/763/89/85676389.geojson
data/856/763/95/85676395-alt-quattroshapes_pg.geojson
data/856/763/95/85676395.geojson
data/856/763/99/85676399-alt-quattroshapes_pg.geojson
data/856/763/99/85676399.geojson
data/856/764/03/85676403-alt-quattroshapes_pg.geojson
data/856/764/03/85676403.geojson
data/856/764/07/85676407-alt-quattroshapes_pg.geojson
data/856/764/07/85676407.geojson
data/856/764/13/85676413-alt-quattroshapes_pg.geojson
data/856/764/13/85676413.geojson
data/856/764/15/85676415-alt-quattroshapes_pg.geojson
data/856/764/15/85676415.geojson
data/856/764/19/85676419-alt-quattroshapes_pg.geojson
data/856/764/19/85676419.geojson
data/856/764/23/85676423-alt-quattroshapes_pg.geojson
data/856/764/23/85676423.geojson
data/856/764/29/85676429-alt-quattroshapes_pg.geojson
data/856/764/29/85676429.geojson
data/856/764/33/85676433-alt-quattroshapes_pg.geojson
data/856/764/33/85676433.geojson
data/856/764/37/85676437-alt-quattroshapes_pg.geojson
data/856/764/37/85676437.geojson
data/890/437/255/890437255.geojson
data/890/443/015/890443015.geojson
```

**Comment by stepps00** [comment]
@noizde - yes, I can handle the export of each of these features.

I will copy your changes into a new branch, handle the export, and merge from there. I'll keep this issue open until then and ping you with anything that comes up. Thanks again!

**Comment by stepps00** [comment]
Update: I've copied all changes into a new local branch and exportified all records. I've noticed some issues with the superseding work, but I'm hoping to resolve them by week's end.

**Comment by stepps00** [comment]
Hey @noizde - thanks for all your work to update the admin records in the Philippines. I copied your work over to https://github.com/whosonfirst-data/whosonfirst-data/pull/1267, processed each record through our export code, then updated the hierarchies of any descendant.

I'm going to close this PR in preference of https://github.com/whosonfirst-data/whosonfirst-data/pull/1267.. lets continue the conversation there.

**Pull request closed without merging**
